// Flow definitions: ic
flowRegistry['ic_ops'] = {
  title: 'IC \u2014 Integrated Circuits',
  nodes: [
    ['root',    'IC System',                          'start', 'Sub-circuit wrapper: file-backed or embedded'],
    ['open',    'Open Sub-Circuit\n(Double-Click)',    'key', 'Embedded: inline tab. File-backed: file tab.', 'ic_open_sub'],
    ['embed',   'Embed\n(File \u2192 Inline)',        'key', 'Read file, register blob, convert instances', 'ic_embed'],
    ['extract', 'Extract\n(Inline \u2192 File)',      'key', 'Write blob to disk, convert instances back', 'ic_extract'],
    ['registry','IC Registry\n(Blob Management)',       'step', ''],
    ['reg_emb', 'Embed by File',                       'key', 'Atomic: find targets, register, reload', 'icreg_embed'],
    ['reg_ext', 'Extract to File',                     'key', 'Atomic: write to disk, convert, remove blob', 'icreg_extract'],
    ['reg_sc',  'Make Self-Contained',                 'key', 'Recursive: embed all file deps into blob', 'icreg_self_contained'],
  ],
  edges: [
    ['root',     'open'],
    ['root',     'embed'],
    ['root',     'extract'],
    ['root',     'registry'],
    ['embed',    'reg_emb'],
    ['extract',  'reg_ext'],
    ['registry', 'reg_sc'],
  ]
};

flowRegistry['ic_open_sub'] = {
  title: 'Open Sub-Circuit',
  nodes: [
        ['start',       'User double-clicks\nan IC element',           'start',    ''],
        ['emit',        'Request open\nsub-circuit',                    'step', 'Signal carries IC element ID, blob name (if embedded), file path (if file-backed)'],
        ['relay',       'Scene relays request\nto MainWindow',          'step',     ''],
        ['d_blob',      'Blob name\nempty?',                            'decision', ''],
        ['d_file',      'File path\nempty?',                            'decision', ''],
        ['dead',        'No-op\n(no source data)',                      'error',    ''],
        ['open_file',   'Open as file tab',                             'end',      'Opens the .panda file as a normal file tab (not inline)'],
        ['d_tab',       'Active tab\nexists?',                          'decision', ''],
        ['no_tab',      'Abort',                                        'error',    'No active workspace tab'],
        ['fetch',       'Fetch blob bytes\nfrom IC Registry',           'step',     ''],
        ['open_ic',     'Open IC in tab',                               'key',      'Core function for opening inline IC tabs'],
        ['d_open',      'Tab already open\nfor this blob?',             'decision', 'Scan all tabs for matching blob + parent'],
        ['switch_tab',  'Switch to\nexisting tab',                      'end',      ''],
        ['create',      'Create new tab',                               'step',     ''],
        ['load', 'Load from blob', 'key', 'Deserializes blob into new inline IC scene', 'ws_load_blob'],
        ['resize',      'Resize scene',                                 'step',     'Tighten scene rect for viewport'],
        ['ui_cfg', 'Configure inline tab UI:\nset title, hide\nIC management buttons', 'step', ''],
        ['connect', 'Connect save signal\nto parent workspace', 'end', 'Ctrl+S in child tab propagates blob updates back to parent', 'ws_child_blob'],
      ],
  edges: [
        ['start',     'emit'],
        ['emit',      'relay'],
        ['relay',     'd_blob'],
        ['d_blob',    'd_tab',      'No \u2014 embedded'],
        ['d_blob',    'd_file',     'Yes \u2014 no blob'],
        ['d_file',    'dead',       'Yes'],
        ['d_file',    'open_file',  'No'],
        ['d_tab',     'no_tab',     'No'],
        ['d_tab',     'fetch',      'Yes'],
        ['fetch',     'open_ic'],
        ['open_ic',   'd_open'],
        ['d_open',    'switch_tab', 'Yes'],
        ['d_open',    'create',     'No'],
        ['create',    'load'],
        ['load',      'resize'],
        ['resize',    'ui_cfg'],
        ['ui_cfg',    'connect'],
      ]
};

flowRegistry['ic_embed'] = {
  title: 'Embed (file \u2192 inline)',
  nodes: [
        ['start',     'User triggers embed',                    'start',    'Element editor "Embed" button or IC DropZone'],
        ['fn',        'Embed selected IC',                       'step',     ''],
        ['d_sel',     'Valid selection?\n(IC, file-backed)',      'decision', ''],
        ['r_sel',     'Abort',                                   'error',    'No selection / wrong type / already embedded'],
        ['d_ctx',     'Project saved\nto disk?',                 'decision', 'IC file paths need a base directory to resolve'],
        ['w_ctx',     'Warning:\n"Save project first"',         'error',    ''],
        ['resolve',   'Resolve unique\nblob name',               'key',    'Auto-suffix for uniqueness; prompt if collision'],
        ['d_name',    'Name\nassigned?',                         'decision', 'User may cancel the name dialog'],
        ['r_name',    'Abort',                                   'error',    ''],
        ['fopen',     'Open IC file\nfor reading',               'step',    ''],
        ['d_read',    'File\nreadable?',                         'decision', ''],
        ['w_read',    'Warning:\n"Could not read IC file"',     'error',   ''],
        ['read',      'Read file contents',                      'step',     ''],
        ['embed', 'Embed ICs by file\n(atomic operation)', 'key', 'Find targets, register blob, reload each. See IC Registry drilldown.', 'cmd_update'],
        ['pal',       'Update palette',                          'step',     ''],
        ['done',      'Status: "IC embedded\nsuccessfully"',     'end',      ''],
      ],
  edges: [
        ['start',   'fn'],
        ['fn',      'd_sel'],
        ['d_sel',   'r_sel',    'No'],
        ['d_sel',   'd_ctx',    'Yes'],
        ['d_ctx',   'w_ctx',    'No'],
        ['d_ctx',   'resolve',  'Yes'],
        ['resolve', 'd_name'],
        ['d_name',  'r_name',   'No'],
        ['d_name',  'fopen',    'Yes'],
        ['fopen',   'd_read'],
        ['d_read',  'w_read',   'No'],
        ['d_read',  'read',     'Yes'],
        ['read',    'embed'],
        ['embed',   'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['ic_extract'] = {
  title: 'Extract (inline \u2192 file)',
  nodes: [
        ['start',     'User triggers extract',                  'start',    'Element editor "Extract" button or IC DropZone'],
        ['fn',        'Extract selected IC',                     'step',     ''],
        ['d_sel',     'Valid selection?\n(IC, embedded)',         'decision', ''],
        ['r_sel',     'Abort',                                   'error',    'No selection / wrong type / not embedded'],
        ['d_ctx',     'Project saved\nto disk?',                 'decision', ''],
        ['w_ctx',     'Warning:\n"Save project first"',         'error',    ''],
        ['dlg',       'Save file dialog\n(suggests blob name)',  'step',    ''],
        ['d_file',    'File path\nchosen?',                      'decision', 'User may cancel the save dialog'],
        ['r_file',    'Abort',                                   'error',    ''],
        ['suffix',    'Append ".panda"\nif missing',             'step',     ''],
        ['extract', 'Extract to file\n(atomic operation)', 'key', 'Write to disk, convert instances, remove blob. See IC Registry drilldown.', 'icreg_extract'],
        ['pal',       'Update palette',                          'step',    ''],
        ['done',      'Status: "IC extracted\nto file"',         'end',      ''],
      ],
  edges: [
        ['start',   'fn'],
        ['fn',      'd_sel'],
        ['d_sel',   'r_sel',    'No'],
        ['d_sel',   'd_ctx',    'Yes'],
        ['d_ctx',   'w_ctx',    'No'],
        ['d_ctx',   'dlg',      'Yes'],
        ['dlg',     'd_file'],
        ['d_file',  'r_file',   'No'],
        ['d_file',  'suffix',   'Yes'],
        ['suffix',  'extract'],
        ['extract', 'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['icreg_embed'] = {
  title: 'Embed ICs by File',
  nodes: [
        ['start',      'Embed ICs by file',                              'start', 'Called by embed actions and make-self-contained'],
        ['find',       'Find IC instances\nusing this file',             'step',  'Scan all scene elements for matching file path'],
        ['d_empty',    'Instances\nfound?',                               'decision', ''],
        ['ret0',       'No instances\non canvas',                         'error',    'Caller may create a new embedded IC instead'],
        ['snap_conn',  'Snapshot external\nconnections',                 'step',  'Save every wire attached to target ports'],
        ['snap_data',  'Snapshot element state\nfor undo rollback',      'step',  'Serialize all target ICs for potential rollback'],
        ['reg',        'Register blob\nin IC Registry',                  'key',   'Store file bytes under the blob name'],
        ['loop',       'For each IC instance:\nset blob name,\nreload from blob', 'key', 'Marks as embedded, deserializes blob, rebuilds ports'],
        ['d_ex',       'Error during\nreload?',                           'decision', ''],
        ['rollback',   'Rollback:\nrestore elements,\nremove blob, re-throw', 'error', 'Restores already-mutated elements from snapshot'],
        ['cmd', 'Push undo command', 'end', 'Undo: restore file-backed state + rewire. Redo: re-apply embedded.', 'cmd_update'],
        ['retN',       'Return count\nof converted ICs',                  'end',   ''],
      ],
  edges: [
        ['start',     'find'],
        ['find',      'd_empty'],
        ['d_empty',   'ret0',      'No'],
        ['d_empty',   'snap_conn', 'Yes'],
        ['snap_conn', 'snap_data'],
        ['snap_data', 'reg'],
        ['reg',       'loop'],
        ['loop',      'd_ex'],
        ['d_ex',      'rollback',  'Yes'],
        ['d_ex',      'cmd',       'No'],
        ['cmd',       'retN'],
      ]
};

flowRegistry['icreg_extract'] = {
  title: 'Extract to File',
  nodes: [
        ['start',     'Extract to file',                                  'start', 'Called by extract actions'],
        ['sf_open',   'Open save file\n(atomic write)',                    'step',  ''],
        ['d_open',    'Open\nsucceeded?',                                  'decision', ''],
        ['ex_open',   'Error:\n"Could not open file"',                    'error', ''],
        ['write',     'Write blob data\nto file',                          'step',  ''],
        ['commit',    'Commit file\n(atomic rename)',                      'step',  'Temp file \u2192 final path (no partial writes)'],
        ['d_commit',  'Commit\nsucceeded?',                                'decision', ''],
        ['ex_commit', 'Error:\n"Could not save file"',                    'error', ''],
        ['find',      'Find IC instances\nusing this blob',                'step',  ''],
        ['d_empty',   'Instances\nfound?',                                 'decision', ''],
        ['ret0',      'Blob saved but\nno instances to convert',           'error',    ''],
        ['snap',      'Snapshot connections,\nelement state,\nand current blob', 'step', 'Full undo state captured before mutation'],
        ['loop',      'For each IC instance:\nreload from file',           'key',   'Clears blob name, sets file path, rebuilds ports'],
        ['d_ex',      'Error during\nreload?',                             'decision', ''],
        ['rollback',  'Rollback:\nrestore elements,\nre-throw',           'error', 'Note: disk file is NOT deleted on rollback'],
        ['rm_blob',   'Remove blob\nfrom registry',                        'step',  'Free memory'],
        ['cmd', 'Push undo command', 'end', 'Undo: re-register blob + restore embedded. Redo: re-extract + remove blob.', 'cmd_update'],
        ['retN',      'Return count\nof converted ICs',                    'end',   ''],
      ],
  edges: [
        ['start',     'sf_open'],
        ['sf_open',   'd_open'],
        ['d_open',    'ex_open',   'No'],
        ['d_open',    'write',     'Yes'],
        ['write',     'commit'],
        ['commit',    'd_commit'],
        ['d_commit',  'ex_commit', 'No'],
        ['d_commit',  'find',      'Yes'],
        ['find',      'd_empty'],
        ['d_empty',   'ret0',      'No'],
        ['d_empty',   'snap',      'Yes'],
        ['snap',      'loop'],
        ['loop',      'd_ex'],
        ['d_ex',      'rollback',  'Yes'],
        ['d_ex',      'rm_blob',   'No'],
        ['rm_blob',   'cmd'],
        ['cmd',       'retN'],
      ]
};

flowRegistry['icreg_self_contained'] = {
  title: 'Make Blob Self-Contained',
  nodes: [
        ['start',    'Make blob self-contained',                          'start', 'Recursively resolves all file dependencies into embedded blobs'],
        ['d_vis',    'Already\nvisited?',                                  'decision', 'Circular-reference guard'],
        ['circ',     'Circular reference\ndetected, abort',               'error',   'Breaks the cycle to prevent infinite recursion'],
        ['insert',   'Mark as visited',                                    'step',    ''],
        ['preamble', 'Read preamble\nfrom blob data',                     'step',    'Parse as .panda file: header \u2192 version \u2192 metadata'],
        ['d_meta',   'Version supports\nmetadata?',                        'decision', ''],
        ['ret_old',  'Skip\n(legacy format)',                              'error',    'Nothing to embed in blobs without metadata'],
        ['deser',    'Extract embedded\nsub-blobs from metadata',          'step',    'Already-embedded ICs inside this blob'],
        ['phase1',   'Phase 1: Recurse into\nexisting sub-blobs',         'key', 'For each dependency: update blob data, recurse, pick up changes'],
        ['d_fbic',   'Has file-backed\nIC dependencies?',                  'decision', 'List of .panda files this blob depends on'],
        ['ret_sc',   'Already\nself-contained',                            'end',     'No file dependencies found'],
        ['phase2',   'Phase 2: For each\nfile dependency',                  'key',     ''],
        ['d_dup',    'Already\nembedded?',                                 'decision', ''],
        ['d_exist',  'File exists?',                                       'decision', ''],
        ['w_miss',   'Warning:\n"dependency not found"',                  'error',    ''],
        ['d_rfile',  'File\nreadable?',                                    'decision', ''],
        ['readf',    'Read file and\nstore as blob',                       'step',    ''],
        ['recurse',  'Recurse into\nnew blob',                            'key',     'Ensures the dependency is also self-contained'],
        ['add_emb',  'Add to embedded\nblob registry',                     'step',    ''],
        ['next_f',   'Next file',                                          'step',    ''],
        ['rm_key',   'Remove file\ndependency list',                       'step',    'All file deps now embedded'],
        ['reser', 'Re-serialize blob\nwith updated metadata', 'end', 'Blob updated in-place with all deps embedded', 'ser_header'],
      ],
  edges: [
        ['start',   'd_vis'],
        ['d_vis',   'circ',     'Yes'],
        ['d_vis',   'insert',   'No'],
        ['insert',  'preamble'],
        ['preamble','d_meta'],
        ['d_meta',  'ret_old',  'No'],
        ['d_meta',  'deser',    'Yes'],
        ['deser',   'phase1'],
        ['phase1',  'd_fbic'],
        ['d_fbic',  'ret_sc',   'No'],
        ['d_fbic',  'phase2',   'Yes'],
        ['phase2',  'd_dup'],
        ['d_dup',   'next_f',   'Yes'],
        ['d_dup',   'd_exist',  'No'],
        ['d_exist', 'w_miss',   'No'],
        ['d_exist', 'd_rfile',  'Yes'],
        ['w_miss',  'next_f'],
        ['d_rfile', 'next_f',   'No'],
        ['d_rfile', 'readf',    'Yes'],
        ['readf',   'recurse'],
        ['recurse', 'add_emb'],
        ['add_emb', 'next_f'],
        ['next_f',  'phase2'],
        ['phase2',  'rm_key'],
        ['rm_key',  'reser'],
      ]
};
