// Flow definitions: mainwindow
flowRegistry['mw_ops'] = {
  title: 'MainWindow \u2014 Operations',
  nodes: [
    ['root',  'MainWindow',                     'start', 'Top-level window: menus, toolbars, tab bar'],
    // File operations
    ['file',  'File Operations',                'step',  ''],
    ['new',   'New',                             'key',   'Ctrl+N: create empty tab',        'mw_new_file'],
    ['open',  'Open',                            'key',   'Ctrl+O: file dialog \u2192 load', 'mw_open_file'],
    ['save',  'Save',                            'key',   'Ctrl+S: save to disk or blob',    'mw_save'],
    ['saveas','Save As',                         'key',   'File dialog \u2192 new path',      'mw_save_as'],
    ['reload','Reload',                          'key',   'Close + reopen from disk',         'mw_reload'],
    // Tab management
    ['tabs',  'Tab Management',                  'key',   'Create / close / switch tabs',     'mw_tabs'],
    // Simulation
    ['sim',   'Simulation\nControls',            'key',   'Play/Pause/Restart',               'mw_sim_controls'],
    // Tools
    ['tools', 'Tools',                           'step',  ''],
    ['bwd',   'Open\nBeWavedDolphin',            'key',   'Ctrl+W: waveform editor',          'mw_open_bwd'],
    // IC management
    ['icmgmt','IC Management',                   'step',  ''],
    ['selfco','Make\nSelf-Contained',            'key',   'Embed all file-backed ICs',        'mw_self_contained'],
    ['embed', 'Embed /\nExtract IC',             'key',   'DropZone or element editor',       'mw_embed_dz'],
    ['addic', 'Add / Remove\nEmbedded IC',       'key',  'Palette + button / trash button',   'mw_add_embedded'],
  ],
  edges: [
    ['root',  'file'],
    ['root',  'tabs'],
    ['root',  'sim'],
    ['root',  'tools'],
    ['root',  'icmgmt'],
    ['file',  'new'],
    ['file',  'open'],
    ['file',  'save'],
    ['file',  'saveas'],
    ['file',  'reload'],
    ['tools', 'bwd'],
    ['icmgmt','selfco'],
    ['icmgmt','embed'],
    ['icmgmt','addic'],
  ]
};

flowRegistry['mw_self_contained'] = {
  title: 'Make Self-Contained',
  nodes: [
        ['start',    'Make Self-Contained',                                'start', 'File menu or IC panel button'],
        ['d_tab',    'Active tab\nexists?',                                'decision', ''],
        ['r_tab',    'Abort',                                              'error', ''],
        ['d_ctx',    'Project saved\nto disk?',                            'decision', ''],
        ['w_ctx',    'Warning:\n"Save project first"',                    'error', ''],
        ['collect',  'Collect unique file paths\nfrom file-backed ICs\n(deduplicated)', 'key', ''],
        ['d_files',  'Any file-backed\nICs found?',                        'decision', ''],
        ['msg_none', 'Status:\n"No file-based ICs"',                      'end',   ''],
        ['loop',     'For each unique file path',                          'key',   ''],
        ['fopen',    'Open IC file\nfor reading',                          'step',  ''],
        ['d_read',   'File\nreadable?',                                    'decision', ''],
        ['w_read',   'Warning dialog\n(abort remaining)',                 'error', ''],
        ['read',     'Read file contents',                                 'step',  ''],
        ['resolve',  'Resolve unique\nblob name',                         'step',  ''],
        ['d_name',   'Name\nassigned?',                                    'decision', ''],
        ['r_cancel', 'Abort\n(user cancelled)',                            'error', ''],
        ['embed', 'Embed ICs by file', 'step', '', 'icreg_embed'],
        ['pal',      'Update palette',                                     'step',  ''],
        ['done',     'Status: "Embedded N IC(s).\nCircuit is\nself-contained."', 'end', ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',     'No'],
        ['d_tab',   'd_ctx',     'Yes'],
        ['d_ctx',   'w_ctx',     'No'],
        ['d_ctx',   'collect',   'Yes'],
        ['collect', 'd_files'],
        ['d_files', 'msg_none',  'No'],
        ['d_files', 'loop',      'Yes'],
        ['loop',    'fopen'],
        ['fopen',   'd_read'],
        ['d_read',  'w_read',    'No'],
        ['d_read',  'read',      'Yes'],
        ['read',    'resolve'],
        ['resolve', 'd_name'],
        ['d_name',  'r_cancel',  'No'],
        ['d_name',  'embed',     'Yes'],
        ['embed',   'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mw_embed_dz'] = {
  title: 'Embed via DropZone',
  nodes: [
        ['start',   'Drag file-backed IC\nto embedded zone',              'start', ''],
        ['fn',      'Embed IC by file',                                    'step',  ''],
        ['d_tab',   'Active tab\nexists?',                                 'decision', ''],
        ['r_tab',   'Abort',                                               'error',  ''],
        ['d_ctx',   'Project saved\nto disk?',                             'decision', ''],
        ['w_ctx',   'Warning:\n"Save project first"',                     'error',  ''],
        ['abs',     'Resolve absolute path',                               'step',   ''],
        ['fopen',   'Open IC file\nfor reading',                           'step',   ''],
        ['d_read',  'File\nreadable?',                                     'decision', ''],
        ['w_read',  'Warning:\n"Could not read IC file"',                 'error',  ''],
        ['read',    'Read file contents',                                   'step',   ''],
        ['resolve', 'Resolve unique\nblob name',                           'step',   ''],
        ['d_name',  'Name\nassigned?',                                     'decision', ''],
        ['r_name',  'Abort\n(cancelled)',                                   'error',  ''],
        ['embed', 'Embed ICs by file', 'key', '', 'icreg_embed'],
        ['d_zero',  'No instances\non canvas?',                            'decision', ''],
        ['create',  'Create embedded IC\nin registry',                     'key',    'Appears in palette for drag-to-create'],
        ['pal',     'Update palette',                                       'step',   ''],
        ['done',    'Status: "IC embedded\nsuccessfully"',                  'end',    ''],
      ],
  edges: [
        ['start',   'fn'],
        ['fn',      'd_tab'],
        ['d_tab',   'r_tab',    'No'],
        ['d_tab',   'd_ctx',    'Yes'],
        ['d_ctx',   'w_ctx',    'No'],
        ['d_ctx',   'abs',      'Yes'],
        ['abs',     'fopen'],
        ['fopen',   'd_read'],
        ['d_read',  'w_read',   'No'],
        ['d_read',  'read',     'Yes'],
        ['read',    'resolve'],
        ['resolve', 'd_name'],
        ['d_name',  'r_name',   'No'],
        ['d_name',  'embed',    'Yes'],
        ['embed',   'd_zero'],
        ['d_zero',  'create',   'Yes'],
        ['d_zero',  'pal',      'No'],
        ['create',  'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mw_extract_dz'] = {
  title: 'Extract via DropZone',
  nodes: [
        ['start',   'Drag embedded IC\nto file-based zone',               'start', ''],
        ['fn',      'Extract IC by\nblob name',                            'step',  ''],
        ['d_tab',   'Active tab\nexists?',                                 'decision', ''],
        ['r_tab',   'Abort',                                               'error',  ''],
        ['d_ctx',   'Project saved\nto disk?',                             'decision', ''],
        ['w_ctx',   'Warning:\n"Save project first"',                     'error',  ''],
        ['d_has',   'Blob exists\nin registry?',                           'decision', ''],
        ['r_nob',   'Abort\n(blob not found)',                             'error',  ''],
        ['dlg',     'Save file dialog\n(suggests blob name)',              'step',  ''],
        ['d_file',  'File path\nchosen?',                                  'decision', ''],
        ['r_cancel','Abort\n(cancelled)',                                   'error',  ''],
        ['suffix',  'Append ".panda"\nif missing',                         'step',   ''],
        ['extract', 'Extract to file', 'key', 'May throw on disk write failure', 'icreg_extract'],
        ['pal',     'Update palette',                                       'step',   ''],
        ['done',    'Status: "IC extracted\nto file"',                      'end',    ''],
      ],
  edges: [
        ['start',   'fn'],
        ['fn',      'd_tab'],
        ['d_tab',   'r_tab',     'No'],
        ['d_tab',   'd_ctx',     'Yes'],
        ['d_ctx',   'w_ctx',     'No'],
        ['d_ctx',   'd_has',     'Yes'],
        ['d_has',   'r_nob',     'No'],
        ['d_has',   'dlg',       'Yes'],
        ['dlg',     'd_file'],
        ['d_file',  'r_cancel',  'No'],
        ['d_file',  'suffix',    'Yes'],
        ['suffix',  'extract'],
        ['extract', 'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mw_add_embedded'] = {
  title: 'Add Embedded IC',
  nodes: [
        ['start',   '"+" button in\nEmbedded ICs palette',                 'start', ''],
        ['d_tab',   'Active tab\nexists?',                                 'decision', ''],
        ['r_tab',   'Abort',                                               'error',  ''],
        ['dlg',     'Open file dialog\n(select .panda file)',              'step', ''],
        ['d_file',  'File\nselected?',                                     'decision', ''],
        ['r_cancel','Abort\n(cancelled)',                                   'error',  ''],
        ['fopen',   'Open file\nfor reading',                               'step',   ''],
        ['d_read',  'File\nreadable?',                                     'decision', ''],
        ['w_read',  'Warning:\n"Could not read file"',                    'error',  ''],
        ['read',    'Read file contents',                                   'step',   ''],
        ['resolve', 'Resolve unique\nblob name',                           'step',   ''],
        ['d_name',  'Name\nassigned?',                                     'decision', ''],
        ['r_name',  'Abort\n(cancelled)',                                   'error',  ''],
        ['cmd',     'Register blob\n(undoable)',                            'key',    'Registers blob without converting any existing ICs. Undo: unregisters.'],
        ['pal',     'Update palette',                                       'end',    'Blob appears in palette; user drags it to create instances'],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',     'No'],
        ['d_tab',   'dlg',       'Yes'],
        ['dlg',     'd_file'],
        ['d_file',  'r_cancel',  'No'],
        ['d_file',  'fopen',     'Yes'],
        ['fopen',   'd_read'],
        ['d_read',  'w_read',    'No'],
        ['d_read',  'read',      'Yes'],
        ['read',    'resolve'],
        ['resolve', 'd_name'],
        ['d_name',  'r_name',    'No'],
        ['d_name',  'cmd',       'Yes'],
        ['cmd',     'pal'],
      ]
};

flowRegistry['mw_remove_embedded'] = {
  title: 'Remove Embedded IC',
  nodes: [
        ['start',   'Trash button in\nEmbedded ICs palette',              'start', ''],
        ['d_tab',   'Active tab\nexists?',                                 'decision', ''],
        ['r_tab',   'Abort',                                               'error',  ''],
        ['fn',      'Remove embedded IC',                                   'step',   ''],
        ['collect',  'Collect all IC instances\nmatching this blob\n+ their wires', 'key', 'Both input and output port connections included'],
        ['d_del',    'Instances\non canvas?',                              'decision', ''],
        ['skip',     'Skip deletion',                                       'step',   'No instances on canvas, only blob in registry'],
        ['del', 'Delete instances\n(undoable)', 'step', 'Removes all instances and their wires', 'cmd_delete'],
        ['rm',       'Remove blob\nfrom registry',                         'step',   ''],
        ['pal',      'Update palette',                                      'end',    ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',    'No'],
        ['d_tab',   'fn',       'Yes'],
        ['fn',      'collect'],
        ['collect',  'd_del'],
        ['d_del',    'skip',    'No'],
        ['d_del',    'del',     'Yes'],
        ['skip',     'rm'],
        ['del',      'rm'],
        ['rm',       'pal'],
      ]
};

flowRegistry['mw_new_file'] = {
  title: 'New File',
  nodes: [
        ['start',   'User: File \u2192 New\nor Ctrl+N',           'start',  ''],
        ['fn',      'New file action',                              'step',   ''],
        ['create',  'Create new tab',                               'key',    'Creates a new workspace, connects signals, adds tab, selects it'],
        ['ws',      'New Workspace\n(Scene + View + Sim)',          'step',   ''],
        ['fmode',   'Inherit fast-mode\nsetting',                   'step',   ''],
        ['theme',   'Apply current theme',                          'step',   ''],
        ['addtab',  'Add tab:\n"New Project"',                      'step',   ''],
        ['select',  'Select new tab',                               'end',    'Triggers tab-changed signal'],
      ],
  edges: [
        ['start',  'fn'],
        ['fn',     'create'],
        ['create', 'ws'],
        ['ws',     'fmode'],
        ['fmode',  'theme'],
        ['theme',  'addtab'],
        ['addtab', 'select'],
      ]
};

flowRegistry['mw_open_file'] = {
  title: 'Open File',
  nodes: [
        ['start',   'User: File \u2192 Open\nor Ctrl+O',          'start',  ''],
        ['dlg',     'Open file dialog',                             'step',   'Suggests ./Examples if no file is currently open'],
        ['d_empty', 'File\nselected?',                              'decision','User may cancel the dialog'],
        ['r_empty', 'Abort',                                        'error',  ''],
        ['load',    'Load .panda file',                              'key',    ''],
        ['create',  'Create new tab',                                'step',   ''],
        ['ws_load', 'Load file into\nworkspace',                    'step',   '', 'ws_load_file'],
        ['resize',  'Resize scene',                                  'step',   'Tighten scene rect to loaded items'],
        ['pal',     'Update IC lists',                               'step',   ''],
        ['done',    'Status:\n"File loaded successfully"',           'end',    ''],
      ],
  edges: [
        ['start',   'dlg'],
        ['dlg',     'd_empty'],
        ['d_empty', 'r_empty', 'No'],
        ['d_empty', 'load',    'Yes'],
        ['load',    'create'],
        ['create',  'ws_load'],
        ['ws_load', 'resize'],
        ['resize',  'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mw_save'] = {
  title: 'Save',
  nodes: [
        ['start',   'User: File \u2192 Save\nor Ctrl+S',          'start',  ''],
        ['d_tab',   'Active tab\nexists?',                          'decision',''],
        ['r_tab',   'Abort',                                        'error',  ''],
        ['d_inline','Inline IC tab?',                               'decision','Inline IC tabs serialize to blob, no file dialog'],
        ['blob', 'Save as blob', 'end', 'Delegates to workspace inline save path', 'ws_save_disk'],
        ['d_file',  'Project previously\nsaved?',                   'decision','Has the project ever been saved to disk?'],
        ['fn_ok',   'Use existing\nfile path',                      'step',   ''],
        ['dlg',     'Save file dialog',                             'step',   'Prompted because project was never saved'],
        ['d_dlg',   'File path\nchosen?',                           'decision','User may cancel'],
        ['r_dlg',   'Abort',                                        'error',  ''],
        ['suffix',  'Append ".panda"\nif missing',                  'step',   ''],
        ['save',    'Save to file', 'key', '', 'ws_save_disk'],
        ['pal',     'Update IC list',                               'step',   ''],
        ['done',    'Status:\n"File saved successfully"',           'end',    ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',    'No'],
        ['d_tab',   'd_inline', 'Yes'],
        ['d_inline','blob',     'Yes'],
        ['d_inline','d_file',   'No'],
        ['d_file',  'fn_ok',    'Yes'],
        ['d_file',  'dlg',      'No'],
        ['dlg',     'd_dlg'],
        ['d_dlg',   'r_dlg',    'No'],
        ['d_dlg',   'suffix',   'Yes'],
        ['fn_ok',   'save'],
        ['suffix',  'save'],
        ['save',    'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mw_save_as'] = {
  title: 'Save As',
  nodes: [
        ['start',   'User: File \u2192 Save As',                   'start',  ''],
        ['d_tab',   'Active tab\nexists?',                          'decision',''],
        ['r_tab',   'Abort',                                        'error',  ''],
        ['dlg',     'Save file dialog',                             'step',   'Suggests current file path'],
        ['d_empty', 'File path\nchosen?',                           'decision','User may cancel'],
        ['r_empty', 'Abort',                                        'error',  ''],
        ['suffix',  'Append ".panda"\nif missing',                  'step',   ''],
        ['save', 'Save to file', 'key', '', 'ws_save_disk'],
        ['done',    'Status:\n"File saved successfully"',           'end',    ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',    'No'],
        ['d_tab',   'dlg',      'Yes'],
        ['dlg',     'd_empty'],
        ['d_empty', 'r_empty',  'No'],
        ['d_empty', 'suffix',   'Yes'],
        ['suffix',  'save'],
        ['save',    'done'],
      ]
};

flowRegistry['mw_reload'] = {
  title: 'Reload File',
  nodes: [
        ['start',   'User: File \u2192 Reload',                    'start',  ''],
        ['d_ok',    'File exists and\nactive tab open?',           'decision',''],
        ['r_no',    'Abort',                                        'error',  'No file to reload or no active tab'],
        ['file',    'Get current\nfile path',                       'step',   ''],
        ['close',   'Close current tab',                            'step',   'May prompt for unsaved changes'],
        ['load',    'Load .panda file',                              'key',    'Create new tab + load + resize scene + update palette'],
      ],
  edges: [
        ['start', 'd_ok'],
        ['d_ok',  'r_no',  'No'],
        ['d_ok',  'file',  'Yes'],
        ['file',  'close'],
        ['close', 'load'],
      ]
};

flowRegistry['mw_tabs'] = {
  title: 'Tab Management',
  nodes: [
        ['create',    'Create new tab',                             'start',  ''],
        ['ws',        'New Workspace\n(Scene + View + Sim)',        'step',   ''],
        ['connect',   'Connect file-changed\nsignal',              'step', ''],
        ['addtab',    'Add tab to tab bar',                         'step',   ''],
        ['sel',       'Select new tab',                             'step',   'Triggers tab-changed handler'],
        ['tc',        'Tab changed',                                'key',    'Called whenever the active tab changes'],
        ['disc',      'Disconnect old tab\n(stop sim, unwire)',    'step',   ''],
        ['d_neg',     'All tabs\nclosed?',                          'decision',''],
        ['reset',     'Reset state:\nclear current tab\nand palette', 'error', ''],
        ['set_cur',   'Set current tab\nto new workspace',          'step',   ''],
        ['conn_tab',  'Connect new tab\n(wire signals, start sim,\nupdate palette)', 'key', ''],
        ['close_fn',  'Close tab',                                  'key',    ''],
        ['switch_to', 'Activate the tab\nbeing closed',            'step',   ''],
        ['d_dirty',   'Unsaved\nchanges?',                         'decision',''],
        ['clean',     'No unsaved changes\n\u2192 proceed',        'step',   ''],
        ['confirm',   'Prompt user:\nSave / Discard / Cancel',     'step',   ''],
        ['d_btn',     'User chose?',                                'decision',''],
        ['cancel',    'Cancel close',                               'error',  ''],
        ['do_save',   'Save',                                       'step',   ''],
        ['d_save_ok', 'Save\nsucceeded?',                          'decision',''],
        ['save_err',  'Error dialog:\nclose anyway?',              'error',  ''],
        ['d_anyway',  'Close\nanyway?',                             'decision',''],
        ['r_no2',     'Cancel close',                               'error',  ''],
        ['delete',    'Remove tab\nand destroy workspace',         'end', ''],
      ],
  edges: [
        ['create',    'ws'],
        ['ws',        'connect'],
        ['connect',   'addtab'],
        ['addtab',    'sel'],
        ['sel',       'tc'],
        ['tc',        'disc'],
        ['disc',      'd_neg'],
        ['d_neg',     'reset',    'Yes'],
        ['d_neg',     'set_cur',  'No'],
        ['set_cur',   'conn_tab'],
        ['close_fn',  'switch_to'],
        ['switch_to', 'd_dirty'],
        ['d_dirty',   'clean',    'No'],
        ['d_dirty',   'confirm',  'Yes'],
        ['clean',     'delete'],
        ['confirm',   'd_btn'],
        ['d_btn',     'cancel',   'Cancel'],
        ['d_btn',     'delete',   'Discard'],
        ['d_btn',     'do_save',  'Yes'],
        ['do_save',   'd_save_ok'],
        ['d_save_ok', 'delete',   'Yes'],
        ['d_save_ok', 'save_err', 'No'],
        ['save_err',  'd_anyway'],
        ['d_anyway',  'delete',   'Yes'],
        ['d_anyway',  'r_no2',    'No'],
      ]
};

flowRegistry['mw_sim_controls'] = {
  title: 'Simulation Controls',
  nodes: [
        ['play',     'User: Play/Pause\ntoggle button',            'start',  ''],
        ['d_tab',    'Active tab\nexists?',                         'decision',''],
        ['r_tab',    'Abort',                                       'error',  ''],
        ['d_chk',    'Checked?',                                    'decision',''],
        ['start_s', 'Start simulation', 'end', 'Starts the 1ms timer update loop', 'sim_ops'],
        ['stop_s', 'Stop simulation', 'end', 'Stops the timer', 'sim_ops'],
        ['restart',  'User: Restart button',                        'start',  ''],
        ['d_tab2',   'Active tab\nexists?',                         'decision',''],
        ['r_tab2',   'Abort',                                       'error',  ''],
        ['do_rst', 'Restart simulation', 'end', 'Stop + reset state + start', 'sim_ops'],
      ],
  edges: [
        ['play',    'd_tab'],
        ['d_tab',   'r_tab',    'No'],
        ['d_tab',   'd_chk',    'Yes'],
        ['d_chk',   'start_s',  'Yes'],
        ['d_chk',   'stop_s',   'No'],
        ['restart', 'd_tab2'],
        ['d_tab2',  'r_tab2',   'No'],
        ['d_tab2',  'do_rst',   'Yes'],
      ]
};

flowRegistry['mw_open_bwd'] = {
  title: 'Open BeWavedDolphin',
  nodes: [
        ['start',   'User: Tools \u2192 Waveform\nor Ctrl+W',     'start',  ''],
        ['d_tab',   'Active tab\nexists?',                          'decision',''],
        ['r_tab',   'Abort',                                        'error',  ''],
        ['create', 'Create waveform editor\nlinked to circuit', 'key', '', 'bwd_ops'],
        ['wave',    'Load or create\nwaveform data',                'step',   'Loads existing .dolphin file if available, or creates blank waveform'],
        ['show', 'Show editor window', 'end', '', 'bwd_ops'],
      ],
  edges: [
        ['start',  'd_tab'],
        ['d_tab',  'r_tab',   'No'],
        ['d_tab',  'create',  'Yes'],
        ['create', 'wave'],
        ['wave',   'show'],
      ]
};
