// Flow definitions: mainwindow
flowRegistry['mainwindow_ops'] = {
  title: 'MainWindow \u2014 IC Management UI',
  nodes: [
    ['f0', '\u2460 Make Self-Contained', 'key', '', 'mainwindow_u2460_make_selfcontained'],
    ['f1', '\u2461 Embed via DropZone', 'key', '', 'mainwindow_u2461_embed_via_dropzone'],
    ['f2', '\u2462 Extract via DropZone', 'key', '', 'mainwindow_u2462_extract_via_dropzone'],
    ['f3', '\u2463 Add Embedded IC', 'key', '', 'mainwindow_u2463_add_embedded_ic'],
    ['f4', '\u2464 Remove Embedded IC', 'key', '', 'mainwindow_u2464_remove_embedded_ic'],
    ['f5', '\u2466 New File', 'key', '', 'mainwindow_u2466_new_file'],
    ['f6', '\u2467 Open File', 'key', '', 'mainwindow_u2467_open_file'],
    ['f7', '\u2468 Save', 'key', '', 'mainwindow_u2468_save'],
    ['f8', '\u2469 Save As', 'key', '', 'mainwindow_u2469_save_as'],
    ['f9', '\u246a Reload File', 'key', '', 'mainwindow_u246a_reload_file'],
    ['f10', '\u246b Tab Management', 'key', '', 'mainwindow_u246b_tab_management'],
    ['f11', '\u246c Simulation Controls', 'key', '', 'mainwindow_u246c_simulation_controls'],
    ['f12', '\u246d Open BeWavedDolphin', 'key', '', 'mainwindow_u246d_open_bewaveddolphin']
  ],
  edges: [
    ['f0', 'f1'],
    ['f1', 'f2'],
    ['f2', 'f3'],
    ['f3', 'f4'],
    ['f4', 'f5'],
    ['f5', 'f6'],
    ['f6', 'f7'],
    ['f7', 'f8'],
    ['f8', 'f9'],
    ['f9', 'f10'],
    ['f10', 'f11'],
    ['f11', 'f12']
  ]
};

flowRegistry['mainwindow_u2460_make_selfcontained'] = {
  title: '\u2460 Make Self-Contained',
  nodes: [
        ['start',    'makeSelfContained()',                                'start', 'File menu \u2192 "Make file self-contained", or IC panel button'],
        ['d_tab',    'm_currentTab\nnull?',                                'decision', ''],
        ['r_tab',    'return',                                             'error', ''],
        ['d_ctx',    'contextDir\nempty?',                                 'decision', ''],
        ['w_ctx',    'Warning:\n"Save project first"',                    'error', ''],
        ['collect',  'Collect unique file paths:\nfor IC where !isEmbedded()\nadd ic->file() (dedup)', 'key', ''],
        ['d_files',  'uniqueFiles\nempty?',                                'decision', ''],
        ['msg_none', 'statusBar:\n"No file-based ICs"',                   'end',   ''],
        ['loop',     'For each unique file path',                          'key',   ''],
        ['fopen',    'QFile::open(contextDir/icFile)',                      'step',  ''],
        ['d_read',   'File\nreadable?',                                    'decision', ''],
        ['w_read',   'Warning dialog\nbreak (abort remaining)',           'error', 'Note: break, not continue \u2014 stops the whole loop'],
        ['read',     'fileBytes = readAll()',                               'step',  ''],
        ['resolve',  'resolveUniqueBlobName',                              'step',  ''],
        ['d_name',   'blobName\nempty?',                                   'decision', ''],
        ['r_cancel', 'break\n(user cancelled)',                            'error', ''],
        ['embed',    'totalEmbedded +=\nembedICsByFile(path, bytes, name)', 'step', ''],
        ['pal',      'palette\u2192updateEmbeddedICList',                  'step',  ''],
        ['done',     'statusBar:\n"Embedded N IC(s).\nCircuit is self-contained."', 'end', ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',     'Yes'],
        ['d_tab',   'd_ctx',     'No'],
        ['d_ctx',   'w_ctx',     'Yes'],
        ['d_ctx',   'collect',   'No'],
        ['collect', 'd_files'],
        ['d_files', 'msg_none',  'Yes'],
        ['d_files', 'loop',      'No'],
        ['loop',    'fopen'],
        ['fopen',   'd_read'],
        ['d_read',  'w_read',    'No'],
        ['d_read',  'read',      'Yes'],
        ['read',    'resolve'],
        ['resolve', 'd_name'],
        ['d_name',  'r_cancel',  'Yes'],
        ['d_name',  'embed',     'No'],
        ['embed',   'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mainwindow_u2461_embed_via_dropzone'] = {
  title: '\u2461 Embed via DropZone',
  nodes: [
        ['start',   'ICDropZone:\ndrag file-based \u2192 embedded zone',  'start', 'embedByFileRequested(fileName)'],
        ['fn',      'embedICByFile(fileName)',                             'step',  ''],
        ['d_tab',   'm_currentTab\nnull?',                                 'decision', ''],
        ['r_tab',   'return',                                              'error',  ''],
        ['d_ctx',   'contextDir\nempty?',                                  'decision', ''],
        ['w_ctx',   'Warning:\n"Save project first"',                     'error',  ''],
        ['abs',     'absolutePath =\ncontextDir / fileName',              'step',   ''],
        ['fopen',   'QFile::open(ReadOnly)',                               'step',   ''],
        ['d_read',  'File\nreadable?',                                     'decision', ''],
        ['w_read',  'Warning:\n"Could not read IC file"',                 'error',  ''],
        ['read',    'fileBytes = readAll()',                                'step',   ''],
        ['resolve', 'resolveUniqueBlobName',                               'step',   ''],
        ['d_name',  'blobName\nempty?',                                    'decision', ''],
        ['r_name',  'return\n(cancelled)',                                 'error',  ''],
        ['embed',   'ICRegistry::embedICsByFile\n(absPath, bytes, name)',  'key',    ''],
        ['d_zero',  'Returned 0?\n(no instances)',                         'decision', ''],
        ['create',  'createEmbeddedIC\n(name, bytes, dir)',               'key',    'Creates a fresh blob in registry so it appears in palette for drag-to-create'],
        ['pal',     'palette\u2192updateEmbeddedICList',                   'step',   ''],
        ['done',    'statusBar:\n"IC embedded successfully"',              'end',    ''],
      ],
  edges: [
        ['start',   'fn'],
        ['fn',      'd_tab'],
        ['d_tab',   'r_tab',    'Yes'],
        ['d_tab',   'd_ctx',    'No'],
        ['d_ctx',   'w_ctx',    'Yes'],
        ['d_ctx',   'abs',      'No'],
        ['abs',     'fopen'],
        ['fopen',   'd_read'],
        ['d_read',  'w_read',   'No'],
        ['d_read',  'read',     'Yes'],
        ['read',    'resolve'],
        ['resolve', 'd_name'],
        ['d_name',  'r_name',   'Yes'],
        ['d_name',  'embed',    'No'],
        ['embed',   'd_zero'],
        ['d_zero',  'create',   'Yes'],
        ['d_zero',  'pal',      'No'],
        ['create',  'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mainwindow_u2462_extract_via_dropzone'] = {
  title: '\u2462 Extract via DropZone',
  nodes: [
        ['start',   'ICDropZone:\ndrag embedded \u2192 file-based zone',  'start', 'extractByBlobNameRequested(blobName)'],
        ['fn',      'extractICByBlobName\n(blobName)',                     'step',  ''],
        ['d_tab',   'm_currentTab\nnull?',                                 'decision', ''],
        ['r_tab',   'return',                                              'error',  ''],
        ['d_ctx',   'contextDir\nempty?',                                  'decision', ''],
        ['w_ctx',   'Warning:\n"Save project first"',                     'error',  ''],
        ['d_has',   'reg->hasBlob\n(blobName)?',                           'decision', ''],
        ['r_nob',   'return\n(blob not found)',                            'error',  ''],
        ['dlg',     'FileDialog::getSaveFileName\nsuggests blobName.panda', 'step',  ''],
        ['d_file',  'fileName\nempty?',                                    'decision', ''],
        ['r_cancel','return\n(cancelled)',                                  'error',  ''],
        ['suffix',  'Append ".panda"\nif missing',                         'step',   ''],
        ['extract', 'ICRegistry::extractToFile\n(blobName, fileName)',     'key',    'May throw PANDACEPTION on disk write failure'],
        ['pal',     'palette\u2192updateICList +\nupdateEmbeddedICList',   'step',   ''],
        ['done',    'statusBar:\n"IC extracted to <file>"',                'end',    ''],
      ],
  edges: [
        ['start',   'fn'],
        ['fn',      'd_tab'],
        ['d_tab',   'r_tab',     'Yes'],
        ['d_tab',   'd_ctx',     'No'],
        ['d_ctx',   'w_ctx',     'Yes'],
        ['d_ctx',   'd_has',     'No'],
        ['d_has',   'r_nob',     'No'],
        ['d_has',   'dlg',       'Yes'],
        ['dlg',     'd_file'],
        ['d_file',  'r_cancel',  'Yes'],
        ['d_file',  'suffix',    'No'],
        ['suffix',  'extract'],
        ['extract', 'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mainwindow_u2463_add_embedded_ic'] = {
  title: '\u2463 Add Embedded IC',
  nodes: [
        ['start',   '"+" button in\nEmbedded ICs palette',                 'start', 'pushButtonAddEmbeddedIC clicked'],
        ['d_tab',   'm_currentTab\nnull?',                                 'decision', ''],
        ['r_tab',   'return',                                              'error',  ''],
        ['dlg',     'FileDialog::getOpenFileName\n\u2192 select .panda file', 'step', ''],
        ['d_file',  'fileName\nempty?',                                    'decision', ''],
        ['r_cancel','return\n(cancelled)',                                  'error',  ''],
        ['fopen',   'QFile::open(ReadOnly)',                                'step',   ''],
        ['d_read',  'File\nreadable?',                                     'decision', ''],
        ['w_read',  'Warning:\n"Could not read file"',                    'error',  ''],
        ['read',    'fileBytes = readAll()',                                 'step',   ''],
        ['resolve', 'resolveUniqueBlobName\n(baseName, scene)',            'step',   ''],
        ['d_name',  'blobName\nempty?',                                    'decision', ''],
        ['r_name',  'return\n(cancelled)',                                  'error',  ''],
        ['cmd',     'RegisterBlobCommand\n(blobName, fileBytes)\n\u2192 undoStack->push', 'key', 'Undoable: registers blob without converting any existing ICs. Undo: unregisters.'],
        ['pal',     'palette\u2192updateEmbeddedICList',                   'end',    'Blob appears in palette; user drags it to create instances'],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',     'Yes'],
        ['d_tab',   'dlg',       'No'],
        ['dlg',     'd_file'],
        ['d_file',  'r_cancel',  'Yes'],
        ['d_file',  'fopen',     'No'],
        ['fopen',   'd_read'],
        ['d_read',  'w_read',    'No'],
        ['d_read',  'read',      'Yes'],
        ['read',    'resolve'],
        ['resolve', 'd_name'],
        ['d_name',  'r_name',    'Yes'],
        ['d_name',  'cmd',       'No'],
        ['cmd',     'pal'],
      ]
};

flowRegistry['mainwindow_u2464_remove_embedded_ic'] = {
  title: '\u2464 Remove Embedded IC',
  nodes: [
        ['start',   'Trash button in\nEmbedded ICs palette',              'start', 'TrashButton::removeEmbeddedIC(blobName)'],
        ['d_tab',   'm_currentTab\nnull?',                                 'decision', ''],
        ['r_tab',   'return',                                              'error',  ''],
        ['fn',      'removeEmbeddedIC(blobName)',                          'step',   ''],
        ['collect',  'Collect all IC instances\nwhere blobName matches\n+ their QNEConnections', 'key', 'Both input and output port connections included'],
        ['d_del',    'toDelete\nnot empty?',                               'decision', ''],
        ['skip',     'Skip deletion command',                              'step',   'No instances on canvas, only blob in registry'],
        ['del',      'DeleteItemsCommand\n(toDelete, scene)\n\u2192 undoStack->push', 'step', 'Undoable: removes all instances and their wires'],
        ['rm',       'icRegistry\u2192removeBlob(blobName)',              'step',   'Free memory: m_blobs.remove(blobName)'],
        ['pal',      'palette\u2192updateEmbeddedICList',                  'end',    ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',    'Yes'],
        ['d_tab',   'fn',       'No'],
        ['fn',      'collect'],
        ['collect',  'd_del'],
        ['d_del',    'skip',    'No'],
        ['d_del',    'del',     'Yes'],
        ['skip',     'rm'],
        ['del',      'rm'],
        ['rm',       'pal'],
      ]
};

flowRegistry['mainwindow_u2466_new_file'] = {
  title: '\u2466 New File',
  nodes: [
        ['start',   'User: File \u2192 New\nor Ctrl+N',           'start',  ''],
        ['fn',      'on_actionNew_triggered()',                     'step',   ''],
        ['create',  'createNewTab()',                               'key',    'Creates a new WorkSpace, connects fileChanged signal, adds tab, selects it'],
        ['ws',      'new WorkSpace(this)',                          'step',   'Scene + GraphicsView + Simulation created'],
        ['fmode',   'view->setFastMode()',                          'step',   'Inherit current fast-mode setting'],
        ['theme',   'scene->updateTheme()',                         'step',   'Apply current theme to the new scene'],
        ['addtab',  'tab->addTab(ws, "New Project")',               'step',   ''],
        ['select',  'tab->setCurrentIndex(last)',                   'end',    'Triggers tabChanged \u2192 connectTab()'],
      ],
  edges: [
        ['start',  'fn'],
        ['fn',     'create'],
        ['create', 'ws'],
        ['ws',     'fmode'],
        ['fmode',  'theme'],
        ['theme',  'addtab'],
        ['addtab', 'select'],
      ]
};

flowRegistry['mainwindow_u2467_open_file'] = {
  title: '\u2467 Open File',
  nodes: [
        ['start',   'User: File \u2192 Open\nor Ctrl+O',          'start',  ''],
        ['dlg',     'FileDialog::getOpenFileName',                  'step',   'Suggests ./Examples if no file is currently open'],
        ['d_empty', 'fileName\nempty?',                             'decision','User cancelled the dialog'],
        ['r_empty', 'return',                                       'error',  ''],
        ['load',    'loadPandaFile(fileName)',                       'key',    ''],
        ['create',  'createNewTab()',                                'step',   'New WorkSpace + tab'],
        ['ws_load', 'm_currentTab->load(fileName)',                 'step',   'Delegates to WorkSpace::load()'],
        ['resize',  'scene->resizeScene()',                          'step',   'Tighten scene rect to loaded items'],
        ['pal',     'updateICList + updateEmbeddedICList',           'step',   ''],
        ['done',    'statusBar:\n"File loaded successfully"',        'end',    ''],
      ],
  edges: [
        ['start',   'dlg'],
        ['dlg',     'd_empty'],
        ['d_empty', 'r_empty', 'Yes'],
        ['d_empty', 'load',    'No'],
        ['load',    'create'],
        ['create',  'ws_load'],
        ['ws_load', 'resize'],
        ['resize',  'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mainwindow_u2468_save'] = {
  title: '\u2468 Save',
  nodes: [
        ['start',   'User: File \u2192 Save\nor Ctrl+S',          'start',  ''],
        ['d_tab',   'm_currentTab\nnull?',                          'decision',''],
        ['r_tab',   'return',                                       'error',  ''],
        ['d_inline','isInlineIC?',                                  'decision','Inline IC tabs serialize to blob, no file dialog'],
        ['blob',    'save(QString())\n\u2192 blob path',           'end',     'Delegates to WorkSpace::save() inline path \u2014 see Workspace drilldown'],
        ['d_file',  'currentFile\nexists?',                         'decision','Has the project ever been saved?'],
        ['fn_ok',   'fileName =\ncurrentFile().absoluteFilePath()', 'step',   ''],
        ['dlg',     'FileDialog::getSaveFileName',                  'step',   'Prompted because project was never saved'],
        ['d_dlg',   'fileName\nempty?',                             'decision','User cancelled'],
        ['r_dlg',   'return',                                       'error',  ''],
        ['suffix',  'Append ".panda"\nif missing',                  'step',   ''],
        ['save',    'save(fileName)',                                'key',    'MainWindow::save() \u2192 m_currentTab->save(fileName)'],
        ['pal',     'updateICList',                                  'step',   ''],
        ['done',    'statusBar:\n"File saved successfully"',         'end',    ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',    'Yes'],
        ['d_tab',   'd_inline', 'No'],
        ['d_inline','blob',     'Yes'],
        ['d_inline','d_file',   'No'],
        ['d_file',  'fn_ok',    'Yes'],
        ['d_file',  'dlg',      'No'],
        ['dlg',     'd_dlg'],
        ['d_dlg',   'r_dlg',    'Yes'],
        ['d_dlg',   'suffix',   'No'],
        ['fn_ok',   'save'],
        ['suffix',  'save'],
        ['save',    'pal'],
        ['pal',     'done'],
      ]
};

flowRegistry['mainwindow_u2469_save_as'] = {
  title: '\u2469 Save As',
  nodes: [
        ['start',   'User: File \u2192 Save As',                   'start',  ''],
        ['d_tab',   'm_currentTab\nnull?',                          'decision',''],
        ['r_tab',   'return',                                       'error',  ''],
        ['dlg',     'FileDialog::getSaveFileName',                  'step',   'Suggests current file path'],
        ['d_empty', 'fileName\nempty?',                             'decision','User cancelled'],
        ['r_empty', 'return',                                       'error',  ''],
        ['suffix',  'Append ".panda"\nif missing',                  'step',   ''],
        ['save',    'save(fileName)',                                'key',    'MainWindow::save() delegates to WorkSpace::save(fileName)'],
        ['done',    'statusBar:\n"File saved successfully"',         'end',    ''],
      ],
  edges: [
        ['start',   'd_tab'],
        ['d_tab',   'r_tab',    'Yes'],
        ['d_tab',   'dlg',      'No'],
        ['dlg',     'd_empty'],
        ['d_empty', 'r_empty',  'Yes'],
        ['d_empty', 'suffix',   'No'],
        ['suffix',  'save'],
        ['save',    'done'],
      ]
};

flowRegistry['mainwindow_u246a_reload_file'] = {
  title: '\u246a Reload File',
  nodes: [
        ['start',   'User: File \u2192 Reload',                    'start',  ''],
        ['d_ok',    'currentFile exists\n&& m_currentTab?',        'decision',''],
        ['r_no',    'return',                                       'error',  'No file to reload or no active tab'],
        ['file',    'file = currentFile\n.absoluteFilePath()',      'step',   ''],
        ['close',   'closeTab(m_tabIndex)',                          'step',   'Closes current tab (may prompt unsaved changes)'],
        ['load',    'loadPandaFile(file)',                           'key',    'createNewTab + load + resizeScene + update palette'],
      ],
  edges: [
        ['start', 'd_ok'],
        ['d_ok',  'r_no',  'No'],
        ['d_ok',  'file',  'Yes'],
        ['file',  'close'],
        ['close', 'load'],
      ]
};

flowRegistry['mainwindow_u246b_tab_management'] = {
  title: '\u246b Tab Management',
  nodes: [
        ['create',    'createNewTab()',                              'start',  ''],
        ['ws',        'new WorkSpace(this)',                         'step',   'Scene + View + Simulation'],
        ['connect',   'connect(ws, fileChanged,\nthis, setCurrentFile)', 'step', ''],
        ['addtab',    'tab->addTab(ws, title)',                     'step',   ''],
        ['sel',       'tab->setCurrentIndex(last)',                  'step',   'Triggers tabChanged()'],
        ['tc',        'tabChanged(newIndex)',                        'key',    'Called whenever the active tab changes'],
        ['disc',      'disconnectTab()',                             'step',   'Stop sim, disconnect signals from old tab'],
        ['d_neg',     'newIndex == -1?\n(all closed)',              'decision',''],
        ['reset',     'Reset state:\nm_currentTab = null\nclear palette', 'error', ''],
        ['set_cur',   'm_currentTab =\ntab->currentWidget()',       'step',   ''],
        ['conn_tab',  'connectTab()',                                'key',    'Wire signals, start sim if playing, update palette, set UI state'],
        ['close_fn',  'closeTab(tabIndex)',                          'key',    ''],
        ['switch_to', 'tab->setCurrentIndex\n(tabIndex)',           'step',   'Activate the tab being closed'],
        ['d_dirty',   'Undo stack\nnot clean?',                     'decision',''],
        ['clean',     'No unsaved changes\n\u2192 proceed',        'step',   ''],
        ['confirm',   'confirmSave(false)',                          'step',   ''],
        ['d_btn',     'User chose?',                                 'decision',''],
        ['cancel',    'return false\n(cancel close)',                'error',  ''],
        ['do_save',   'save()',                                      'step',   ''],
        ['d_save_ok', 'Save\nsucceeded?',                           'decision',''],
        ['save_err',  'QMessageBox::critical\ncloseTabAnyway()?',   'error',  ''],
        ['d_anyway',  'Close\nanyway?',                              'decision',''],
        ['r_no2',     'return false',                                'error',  ''],
        ['delete',    'm_currentTab->deleteLater()\ntab->removeTab()', 'end', ''],
      ],
  edges: [
        ['create',    'ws'],
        ['ws',        'connect'],
        ['connect',   'addtab'],
        ['addtab',    'sel'],
        ['sel',       'tc'],
        ['tc',        'disc'],
        ['disc',      'd_neg'],
        ['d_neg',     'reset',    'Yes'],
        ['d_neg',     'set_cur',  'No'],
        ['set_cur',   'conn_tab'],
        ['close_fn',  'switch_to'],
        ['switch_to', 'd_dirty'],
        ['d_dirty',   'clean',    'No'],
        ['d_dirty',   'confirm',  'Yes'],
        ['clean',     'delete'],
        ['confirm',   'd_btn'],
        ['d_btn',     'cancel',   'Cancel'],
        ['d_btn',     'delete',   'Discard'],
        ['d_btn',     'do_save',  'Yes'],
        ['do_save',   'd_save_ok'],
        ['d_save_ok', 'delete',   'Yes'],
        ['d_save_ok', 'save_err', 'No'],
        ['save_err',  'd_anyway'],
        ['d_anyway',  'delete',   'Yes'],
        ['d_anyway',  'r_no2',    'No'],
      ]
};

flowRegistry['mainwindow_u246c_simulation_controls'] = {
  title: '\u246c Simulation Controls',
  nodes: [
        ['play',     'User: Play/Pause\ntoggle button',            'start',  'Action is checkable; toggled(bool) signal drives start/stop'],
        ['d_tab',    'm_currentTab\nnull?',                         'decision',''],
        ['r_tab',    'return',                                      'error',  ''],
        ['d_chk',    'checked?',                                    'decision',''],
        ['start_s',  'simulation->start()',                          'end',    'Starts the 1ms QTimer update loop'],
        ['stop_s',   'simulation->stop()',                           'end',    'Stops the QTimer'],
        ['restart',  'User: Restart button',                         'start',  'on_actionRestart_triggered()'],
        ['d_tab2',   'm_currentTab\nnull?',                         'decision',''],
        ['r_tab2',   'return',                                      'error',  ''],
        ['do_rst',   'simulation->restart()',                        'end',    'stop() + reset state + start()'],
      ],
  edges: [
        ['play',    'd_tab'],
        ['d_tab',   'r_tab',    'Yes'],
        ['d_tab',   'd_chk',    'No'],
        ['d_chk',   'start_s',  'Yes'],
        ['d_chk',   'stop_s',   'No'],
        ['restart', 'd_tab2'],
        ['d_tab2',  'r_tab2',   'Yes'],
        ['d_tab2',  'do_rst',   'No'],
      ]
};

flowRegistry['mainwindow_u246d_open_bewaveddolphin'] = {
  title: '\u246d Open BeWavedDolphin',
  nodes: [
        ['start',   'User: Tools \u2192 Waveform\nor Ctrl+W',     'start',  ''],
        ['d_tab',   'm_currentTab\nnull?',                          'decision',''],
        ['r_tab',   'return',                                       'error',  ''],
        ['create',  'new BewavedDolphin\n(scene, true, this)',      'key',    'Creates waveform editor window linked to current circuit scene'],
        ['wave',    'createWaveform\n(dolphinFileName)',             'step',   'Loads existing .dolphin file if available, or creates blank waveform'],
        ['show',    'bewavedDolphin->show()',                        'end',    'Shows the waveform editor window'],
      ],
  edges: [
        ['start',  'd_tab'],
        ['d_tab',  'r_tab',   'Yes'],
        ['d_tab',  'create',  'No'],
        ['create', 'wave'],
        ['wave',   'show'],
      ]
};

