// Flow definitions: scene
flowRegistry['scene_ops'] = {
  title: 'Scene \u2014 Circuit Editing',
  nodes: [
    ['root',    'Scene',                             'start', 'QGraphicsScene: owns elements, wires, undo stack'],
    ['mouse',   'Mouse Events\n(press/move/release)','key',  'Selection, dragging, wire drawing', 'scene_mouse'],
    ['clip',    'Clipboard\n(Copy/Cut/Paste)',       'key',  'Serialize selected items, deserialize on paste', 'scene_clipboard'],
    ['del',     'Delete Selected',                    'key',  'Push delete command to undo stack', 'scene_delete'],
    ['xform',   'Rotate / Flip',                      'key',  'Push rotate/flip command to undo stack', 'scene_transform'],
    ['drop',    'Drop Element\nfrom Palette',         'key', 'Build element + push add command', 'scene_drop'],
  ],
  edges: [
    ['root',  'mouse'],
    ['root',  'clip'],
    ['root',  'del'],
    ['root',  'xform'],
    ['root',  'drop'],
  ]
};

flowRegistry['scene_clipboard'] = {
  title: 'Copy / Cut / Paste',
  nodes: [
        ['copy',     'Copy action',                       'start',    ''],
        ['cm_copy',  'Clipboard: copy',                   'key',      ''],
        ['d_sel',    'Selection\nempty?',                  'decision', ''],
        ['clear_cb', 'Clear clipboard',                   'error',    ''],
        ['ser', 'Serialize selected items\nwith centroid offset', 'step', '', 'ser_header'],
        ['blobs',    'Collect embedded IC\nblobs used by selection', 'step',    ''],
        ['set_mime', 'Store in clipboard',                'end',      ''],
        ['cut',      'Cut action',                        'start',    ''],
        ['cm_cut',   'Clipboard: cut',                    'key',      ''],
        ['d_sel2',   'Selection\nempty?',                  'decision', ''],
        ['clear_cb2','Clear clipboard',                   'error',    ''],
        ['ser_del',  'Serialize and delete\nselected items','step', ''],
        ['set_mime2','Store in clipboard',                'end',      ''],
        ['paste',    'Paste action',                      'start',    ''],
        ['cm_paste', 'Clipboard: paste',                  'key',      ''],
        ['d_mime',   'Clipboard has\ndata?',               'decision', ''],
        ['r_mime',   'Abort',                              'error',    ''],
        ['d_blobs',  'Has embedded\nIC blobs?',            'decision', ''],
        ['imp_blob', 'Import blobs into\nIC Registry (skip dupes)','step',''],
        ['d_fmt',    'Valid clipboard\nformat?',           'decision', ''],
        ['r_fmt',    'Abort\n(wrong format)',              'error',    ''],
        ['deser', 'Deserialize, add items,\nreposition at mouse', 'key', 'Clear selection, compute offset from centroid, push add command', 'ser_header'],
      ],
  edges: [
        ['copy',     'cm_copy'],
        ['cm_copy',  'd_sel'],
        ['d_sel',    'clear_cb',  'Yes'],
        ['d_sel',    'ser',       'No'],
        ['ser',      'blobs'],
        ['blobs',    'set_mime'],
        ['cut',      'cm_cut'],
        ['cm_cut',   'd_sel2'],
        ['d_sel2',   'clear_cb2', 'Yes'],
        ['d_sel2',   'ser_del',   'No'],
        ['ser_del',  'set_mime2'],
        ['paste',    'cm_paste'],
        ['cm_paste', 'd_mime'],
        ['d_mime',   'r_mime',    'No'],
        ['d_mime',   'd_blobs',   'Yes'],
        ['d_blobs',  'imp_blob',  'Yes'],
        ['d_blobs',  'd_fmt',     'No'],
        ['imp_blob', 'd_fmt'],
        ['d_fmt',    'r_fmt',     'No'],
        ['d_fmt',    'deser',     'Yes'],
      ]
};

flowRegistry['scene_delete'] = {
  title: 'Delete Selected',
  nodes: [
        ['start',  'Delete action',                        'start',    ''],
        ['sel',    'Get selected items',                    'step',     ''],
        ['d_empty','Selection\nempty?',                    'decision', ''],
        ['r_emp',  'Abort',                                'error',    ''],
        ['clear',  'Clear selection',                       'step',     ''],
        ['cmd',    'Push delete command\nto undo stack',    'key',      '', 'cmd_delete'],
        ['restart', 'Restart simulation', 'end', 'Rebuild sim graph without deleted elements', 'sim_cycle'],
      ],
  edges: [
        ['start',  'sel'],
        ['sel',    'd_empty'],
        ['d_empty','r_emp',   'Yes'],
        ['d_empty','clear',   'No'],
        ['clear',  'cmd'],
        ['cmd',    'restart'],
      ]
};

flowRegistry['scene_transform'] = {
  title: 'Rotate / Flip',
  nodes: [
        ['rot_r',   'Rotate Right',                       'start',    '90\u00b0 clockwise'],
        ['rot_l',   'Rotate Left',                        'start',    '90\u00b0 counter-clockwise'],
        ['rotate',  'Rotate by angle',                    'key',      ''],
        ['d_sel',   'Selection\nempty?',                   'decision', ''],
        ['r_emp',   'Abort',                               'error',    ''],
        ['rot_cmd', 'Push rotate command\nto undo stack',  'end', 'Computes centroid, applies 2D rotation to all positions'],
        ['flip_h',  'Flip Horizontally',                   'start',    ''],
        ['flip_v',  'Flip Vertically',                     'start',    ''],
        ['d_sel2',  'Selection\nempty?',                   'decision', ''],
        ['r_emp2',  'Abort',                               'error',    ''],
        ['flip_cmd','Push flip command\nto undo stack',    'end', 'Flip is involution: undo() calls redo()'],
      ],
  edges: [
        ['rot_r',   'rotate'],
        ['rot_l',   'rotate'],
        ['rotate',  'd_sel'],
        ['d_sel',   'r_emp',    'Yes'],
        ['d_sel',   'rot_cmd',  'No'],
        ['flip_h',  'd_sel2'],
        ['flip_v',  'd_sel2'],
        ['d_sel2',  'r_emp2',   'Yes'],
        ['d_sel2',  'flip_cmd', 'No'],
      ]
};

flowRegistry['scene_drop'] = {
  title: 'Drop Element',
  nodes: [
        ['start',   'Element dropped\non canvas',                  'start',    'From palette drag or Ctrl+drag clone'],
        ['d_fmt',   'Drop source?',                                'decision', ''],
        ['new_elm',  'New element\nfrom palette',                  'step',     'Read: offset, type, IC filename from stream'],
        ['clone',    'Clone drag\n(Ctrl+drag)',                    'step',     'Read: offset, centroid from stream'],
        ['build', 'Build element\nfrom factory', 'key', '', 'ef_build'],
        ['drop_load','Load IC file\n(if applicable)',              'step', ''],
        ['add_cmd',  'Push add command\nto undo stack',             'key',     '', 'cmd_add'],
        ['pos',      'Position at\ndrop location',                 'step',    ''],
        ['select',   'Clear selection,\nselect new element',       'end',''],
        ['deser_c',  'Deserialize items\nfrom clone data',         'key',     ''],
        ['add_cmd2', 'Push add command\nto undo stack',             'step',    '', 'cmd_add'],
        ['repos',    'Reposition items\nby offset from mouse',    'step', ''],
        ['resize',   'Resize scene',                                'end',     ''],
      ],
  edges: [
        ['start',    'd_fmt'],
        ['d_fmt',    'new_elm',   'palette drag'],
        ['d_fmt',    'clone',     'Ctrl+drag'],
        ['new_elm',  'build'],
        ['build',    'drop_load'],
        ['drop_load','add_cmd'],
        ['add_cmd',  'pos'],
        ['pos',      'select'],
        ['clone',    'deser_c'],
        ['deser_c',  'add_cmd2'],
        ['add_cmd2', 'repos'],
        ['repos',    'resize'],
      ]
};

flowRegistry['scene_mouse'] = {
  title: 'Mouse Events',
  nodes: [
        ['press',   'Mouse press',                         'start',    ''],
        ['hover', 'Update wire\nhover feedback', 'step', '', 'conn_create'],
        ['d_item',  'Item at\nclick pos?',                 'decision', ''],
        ['d_port',  'Item is\na port?',                    'decision', ''],
        ['d_editing','Has active\nwire edit?',             'decision', ''],
        ['try_comp', 'Complete or cancel\nthe wire', 'end', '', 'conn_create'],
        ['d_out',   'Output\nport?',                       'decision', ''],
        ['start_w', 'Begin new wire\nfrom output port', 'end', '', 'conn_create'],
        ['d_inp_c', 'Input has\nconnections?',             'decision', ''],
        ['start_i', 'Begin new wire\nfrom empty input', 'end', '', 'conn_create'],
        ['detach',  'Disconnect existing\nwire and drag it', 'end',     ''],
        ['d_btn',   'Left button?',                        'decision', ''],
        ['sel_box', 'Start rubber-band\nselection',        'end',     ''],
        ['ctx', 'Right-click menu', 'end', '', 'ui_menu_dispatch'],
        ['drag',    'Snapshot positions,\nstart dragging',  'step', ''],
        ['move',    'Mouse move',                           'key',     ''],
        ['d_drag',  'Dragging\nelement?',                  'decision', ''],
        ['resize_s','Resize scene,\nensure visible',        'step',    ''],
        ['d_edit',  'Has active\nwire edit?',              'decision', ''],
        ['upd_end', 'Update wire endpoint\nto mouse pos',   'step',    ''],
        ['d_selbox','Selection\nbox active?',              'decision', ''],
        ['upd_rect','Update selection\nrectangle',          'step',''],
        ['release', 'Mouse release',                        'key',     ''],
        ['d_moved', 'Elements\nmoved?',                    'decision', ''],
        ['mov_cmd', 'Push move command\nto undo stack',     'end',     '', 'cmd_move'],
        ['no_move', 'No-op\n(click without drag)',         'step',    ''],
        ['d_wire',  'Has active\nwire edit?',              'decision', ''],
        ['try_c2',  'Complete wire',                        'end',     ''],
      ],
  edges: [
        ['press',    'hover'],
        ['hover',    'd_item'],
        ['d_item',   'd_btn',     'No (empty)'],
        ['d_item',   'd_port',    'Yes'],
        ['d_port',   'd_editing', 'Yes (port)'],
        ['d_port',   'drag',      'No (element)'],
        ['d_editing','try_comp',  'Yes'],
        ['d_editing','d_out',     'No'],
        ['d_out',    'start_w',   'Yes'],
        ['d_out',    'd_inp_c',   'No (input)'],
        ['d_inp_c',  'start_i',   'No'],
        ['d_inp_c',  'detach',    'Yes'],
        ['d_btn',    'sel_box',   'Yes (left)'],
        ['d_btn',    'ctx',       'No (right)'],
        ['drag',     'move'],
        ['move',     'd_drag'],
        ['d_drag',   'resize_s',  'Yes'],
        ['d_drag',   'd_edit',    'No'],
        ['d_edit',   'upd_end',   'Yes'],
        ['d_edit',   'd_selbox',  'No'],
        ['d_selbox', 'upd_rect',  'Yes'],
        ['resize_s', 'release'],
        ['upd_end',  'release'],
        ['upd_rect', 'release'],
        ['release',  'd_moved'],
        ['d_moved',  'mov_cmd',   'Yes'],
        ['d_moved',  'no_move',   'No'],
        ['no_move',  'd_wire'],
        ['d_wire',   'try_c2',    'Yes'],
      ]
};

flowRegistry['scene_mod'] = {
  title: 'Scene',
  nodes: [
    ['f0', 'Ownership & Managers', 'key', '', 'scene_ownership'],
    ['f1', 'Mouse Interactions', 'key', '', 'scene_mouse_old']
  ],
  edges: [
    ['f0', 'f1']
  ]
};

flowRegistry['scene_ownership'] = {
  title: 'Ownership & Managers',
  nodes: [
        ['scene',    'Scene constructed',       'start',    ''],
        ['undo',     'Undo Stack',              'step',     'Undo/Redo via command subclasses'],
        ['sim',      'Simulation',              'key',      '1ms timer, topological sim'],
        ['icreg',    'IC Registry',             'step',     'Caches IC definitions, file watching'],
        ['elemreg',  'Element Registry',        'step',     'ID-based lookup for all items'],
        ['connmgr', 'Connection Manager', 'step', 'Wire creation, validation, hover feedback', 'conn_create'],
        ['clipmgr',  'Clipboard Manager',       'step',     'Copy/Cut/Paste, clone-drag serialization'],
        ['vismgr',   'Visibility Manager',      'step',     'Show/Hide gates and wires'],
        ['propmgr',  'Property Shortcut\nHandler', 'step',  'Keyboard shortcuts for cycling element properties'],
      ],
  edges: [
        ['scene', 'undo',    'owns'],
        ['scene', 'sim',     'owns'],
        ['scene', 'icreg',   'owns'],
        ['scene', 'elemreg', 'owns'],
        ['scene', 'connmgr', 'delegates'],
        ['scene', 'clipmgr', 'delegates'],
        ['scene', 'vismgr',  'delegates'],
        ['scene', 'propmgr', 'delegates'],
      ]
};

flowRegistry['scene_mouse_old'] = {
  title: 'Mouse Interactions',
  nodes: [
        ['press',    'Mouse press',             'start',    'Start selection box, start dragging, start wire'],
        ['move',     'Mouse move',              'step',     'Update drag position, extend wire/selection'],
        ['release', 'Mouse release', 'step', 'Commit move, finish wire, commit selection', 'cmd_move'],
        ['dblclick', 'Double-click',            'step',     'Open IC sub-circuit, toggle input'],
        ['add',      'Add Items',               'step',     'Drop/paste elements'],
        ['del',      'Delete Items',            'step',     'Delete selection'],
        ['mv',       'Move',                    'step',     'Drag elements'],
        ['rot',      'Rotate / Flip',           'step',     'Transform elements'],
        ['upd',      'Update',                  'step',     'Property changes (label, color, freq)'],
        ['split',    'Split',                   'step',     'Insert node into wire'],
        ['morph',    'Morph',                   'step',     'Change element type'],
        ['chgsz',    'Change Input Size',       'step',     'Add/remove ports'],
        ['stale',    'Mark circuit for rebuild', 'key',     'Simulation graph is stale. Next timer tick rebuilds it.'],
      ],
  edges: [
        ['press',    'move'],
        ['move',     'release'],
        ['release',  'add'],
        ['release',  'mv'],
        ['dblclick', 'add'],
        ['press',    'del'],
        ['release',  'rot'],
        ['release',  'upd'],
        ['release',  'split'],
        ['release',  'morph'],
        ['release',  'chgsz'],
        ['add',      'stale'],
        ['del',      'stale'],
        ['mv',       'stale'],
        ['rot',      'stale'],
        ['upd',      'stale'],
        ['split',    'stale'],
        ['morph',    'stale'],
        ['chgsz',    'stale'],
      ]
};
