// Flow definitions: simulation
flowRegistry['sim_ops'] = {
  title: 'Simulation \u2014 Engine',
  nodes: [
    ['root',   'Simulation Engine',                  'start', '1ms timer, 4-phase update, topological sort'],
    ['cycle',  'Update Cycle\n(~1000x/sec)',         'key',  'Clocks \u2192 Inputs \u2192 Logic \u2192 Visual refresh', 'sim_cycle'],
    ['init',   'Initialize\n(Lazy, on first tick)',   'key', 'Collect items, build graph, topological sort', 'sim_init'],
    ['topo',   'Topological Sort\n(Kahn\u2019s algorithm)', 'key', 'Assigns priorities, detects feedback', 'sim_topo_sort'],
    ['settle', 'Iterative Settle\n(Feedback loops)',    'key', 'Loop up to 10x until converged', 'sim_settle'],
  ],
  edges: [
    ['root',   'cycle'],
    ['cycle',  'init'],
    ['init',   'topo'],
    ['cycle',  'settle'],
  ]
};

flowRegistry['sim_init'] = {
  title: 'Initialize Simulation',
  nodes: [
        ['start',   'Initialize Simulation',                    'start',    'Called lazily on first update tick after restart'],
        ['d_scene', 'Scene\navailable?',                        'decision', ''],
        ['r_scene', 'Abort',                                     'error',    ''],
        ['clear',   'Clear all lists:\nclocks, inputs, outputs,\nconnections, sorted', 'step', ''],
        ['items',   'Get scene items\nstable sort by (Y, X)',   'step',    'Deterministic ordering'],
        ['d_one',   'Only 1 item?\n(border rect)',              'decision', ''],
        ['r_one',   'Abort\n(empty scene)',                      'error',    ''],
        ['time',    'Record start time',                         'step',     ''],
        ['cat',     'Categorize items:\nConnections, Clocks,\nInputs, Outputs', 'key', 'Each group stored in a separate list for phased updates'],
        ['d_empty', 'Elements\nempty?',                          'decision', ''],
        ['r_empty', 'Abort',                                     'error',    ''],
        ['init_v',  'Allocate simulation\nvectors per element',  'step',   'Input/output value arrays'],
        ['build_c', 'Build connection graph',                    'step',    'Walk input ports, find source via wire, link predecessors'],
        ['wireless','Connect wireless\nelements',                'step',    'Build Tx label\u2192element map, override Rx predecessors'],
        ['ic_init', 'Initialize IC\nsub-circuits',               'step',   'Recursively build sim graphs for each IC'],
        ['sort',    'Sort elements\nby dependency',              'key',     'Topological sort + feedback detection', 'sim_topo_sort'],
        ['done',    'Ready',                                     'end',      ''],
      ],
  edges: [
        ['start',    'd_scene'],
        ['d_scene',  'r_scene',   'No'],
        ['d_scene',  'clear',     'Yes'],
        ['clear',    'items'],
        ['items',    'd_one'],
        ['d_one',    'r_one',     'Yes'],
        ['d_one',    'time',      'No'],
        ['time',     'cat'],
        ['cat',      'd_empty'],
        ['d_empty',  'r_empty',   'Yes'],
        ['d_empty',  'init_v',    'No'],
        ['init_v',   'build_c'],
        ['build_c',  'wireless'],
        ['wireless', 'ic_init'],
        ['ic_init',  'sort'],
        ['sort',     'done'],
      ]
};

flowRegistry['sim_topo_sort'] = {
  title: 'Topological Sort',
  nodes: [
        ['start',   'Sort Elements\nby Dependency',              'start',    ''],
        ['tx',      'Build wireless\ntransmitter map',           'step',     'Map Tx labels to elements'],
        ['succ',    'Build successor graph',                     'step',    'For each element: who depends on it?'],
        ['topo',    'Topological sort\n(Kahn\u2019s algorithm)', 'key',     ''],
        ['queue',   'Init queue with\nelements having\nno dependencies',  'step',''],
        ['loop',    'Process queue:\npop \u2192 add to sorted\ndecrement successors', 'key', ''],
        ['d_fb',    'Any elements\nnot visited?',                'decision', 'Remaining = feedback nodes'],
        ['no_fb',   'No feedback',                               'step',     ''],
        ['fb',      'Mark feedback nodes',                       'error',    'These elements participate in feedback loops'],
        ['prio',    'Assign priorities\nfrom sorted order',      'step',    'Highest priority = earliest in sorted list'],
        ['done',    'Store sorted elements\nand feedback flags', 'end',''],
      ],
  edges: [
        ['start',  'tx'],
        ['tx',     'succ'],
        ['succ',   'topo'],
        ['topo',   'queue'],
        ['queue',  'loop'],
        ['loop',   'd_fb'],
        ['d_fb',   'no_fb',  'No'],
        ['d_fb',   'fb',     'Yes'],
        ['no_fb',  'prio'],
        ['fb',     'prio'],
        ['prio',   'done'],
      ]
};

flowRegistry['sim_settle'] = {
  title: 'Iterative Settle',
  nodes: [
        ['start',   'Iterative Settle\n(max 10 iterations)',     'start',  'Called when feedback loops detected'],
        ['loop',    'For each iteration',                        'key',     ''],
        ['clear',   'Clear output-changed\nflags on all elements', 'step',    ''],
        ['update', 'Run logic\non all elements', 'step', '', 'ge_logic'],
        ['d_conv',  'Any output\nchanged?',                      'decision',''],
        ['conv',    'Converged',                                  'end',     ''],
        ['next',    'Next iteration',                             'step',    ''],
        ['fail',    'Did not converge',                           'error',   'Simulation may emit warning after 10 iterations'],
      ],
  edges: [
        ['start',  'loop'],
        ['loop',   'clear'],
        ['clear',  'update'],
        ['update', 'd_conv'],
        ['d_conv', 'conv',    'No (settled)',  'seg-left'],
        ['d_conv', 'next',    'Yes (changed)', 'seg-right'],
        ['next',   'loop'],
        ['loop',   'fail'],
      ]
};

flowRegistry['sim_cycle'] = {
  title: 'Simulation Cycle',
  nodes: [
        ['start',      'Start Simulation',                             'start',    ''],
        ['timer',      'Timer fires\nevery 1ms',                      'step',     ''],
        ['update',     'Update\n(~1000x/sec)',                        'key',      'Main simulation loop'],
        ['d_init',     'Initialized?',                                 'decision', 'Lazy init: rebuild sim graph on first tick after restart'],
        ['collect',    'Collect scene items\nsort by (Y, X)',          'step',     'Deterministic ordering, categorize into clocks, inputs, outputs, connections'],
        ['init_vec',   'Allocate simulation\nvectors',                'step',     'Input/output value arrays on each element'],
        ['build_conn', 'Build connection graph', 'step', 'Walk each input port, find source via wire, link predecessors', 'sim_init'],
        ['wireless',   'Connect wireless\nelements',                  'step',     'Build Tx label\u2192element map, override Rx predecessors'],
        ['ic_init', 'Initialize IC\nsub-circuits', 'step', 'Recursively build sim graphs for each IC element', 'sim_init'],
        ['sort', 'Sort elements\nby dependency', 'key', 'Build successor graph, topological sort, assign priorities, detect feedback', 'sim_topo_sort'],
        ['p0',         'Phase 0: Clocks\ncheck elapsed \u2192 toggle', 'step',  'Check wall clock elapsed vs interval; if exceeded \u2192 toggle output'],
        ['p1',         'Phase 1: Inputs\npush state to sim',          'step', 'Push switch/button/rotary state to simulation output slots'],
        ['d_fb',       'Has feedback\nloops?',                         'decision', ''],
        ['single', 'Single pass:\nrun logic in\ntopological order', 'step', 'Highest priority first', 'ge_logic'],
        ['settle',     'Iterative settle\n(loop up to 10x)',          'error',    '1. Clear changed flags 2. Run logic on all 3. Check convergence'],
        ['d_tick',     'Visual tick\ndue?',                            'decision', 'Throttle to ~60fps'],
        ['skip_vis',   'Skip repaint',                                 'step',     ''],
        ['p3',         'Phase 3: Update\noutput port visuals',        'end',      'Push logic values onto wire visuals'],
        ['p4',         'Phase 4: Update\ninput port visuals',         'end',      'Refresh LED/display/buzzer visuals'],
        ['wait',       'Wait for\nnext tick (1ms)',                    'step',     ''],
      ],
  edges: [
        ['start',      'timer'],
        ['timer',      'update'],
        ['update',     'd_init'],
        ['d_init',     'collect',    'No \u2014 initialize'],
        ['d_init',     'p0',         'Yes \u2014 run phases'],
        ['collect',    'init_vec'],
        ['init_vec',   'build_conn'],
        ['build_conn', 'wireless'],
        ['wireless',   'ic_init'],
        ['ic_init',    'sort'],
        ['sort',       'p0'],
        ['p0',         'p1'],
        ['p1',         'd_fb'],
        ['d_fb',       'single',     'No'],
        ['d_fb',       'settle',     'Yes'],
        ['single',     'd_tick'],
        ['settle',     'd_tick'],
        ['d_tick',     'skip_vis',   'No'],
        ['d_tick',     'p3',         'Yes'],
        ['p3',         'p4'],
        ['skip_vis',   'wait'],
        ['p4',         'wait'],
      ]
};
