// Flow definitions: workspace
flowRegistry['ws_ops'] = {
  title: 'Workspace \u2014 Per-Tab Environment',
  nodes: [
    ['root',    'Workspace',                         'start', 'One per open circuit tab: Scene + View + Simulation'],
    ['file_io', 'File I/O',                          'step',  ''],
    ['save',    'Save to Disk',                      'key',   'QSaveFile atomic write, autosave cleanup', 'ws_save_disk'],
    ['load',    'Load from File',                    'key',   'readPandaHeader, migration, deserialize', 'ws_load_file'],
    ['autosave','Autosave',                          'key',   'Periodic temp file, Settings registry', 'ws_autosave'],
    ['inline',  'Inline IC Tab',                     'step',  ''],
    ['blob_l',  'Load from Blob',                    'key',   'Deserialize embedded IC into child tab', 'ws_load_blob'],
    ['blob_s',  'Save as Blob',                      'key',   'Serialize \u2192 emit icBlobSaved to parent', 'ws_save_inline'],
    ['child',   'Receive Child\nBlob Update',       'key',   'onChildICBlobSaved: atomic reload all instances', 'ws_child_blob'],
  ],
  edges: [
    ['root',    'file_io'],
    ['root',    'inline'],
    ['file_io', 'save'],
    ['file_io', 'load'],
    ['file_io', 'autosave'],
    ['inline',  'blob_l'],
    ['inline',  'blob_s'],
    ['blob_s',  'child'],
  ]
};

flowRegistry['ws_load_blob'] = {
  title: 'loadFromBlob',
  nodes: [
        ['start',   'loadFromBlob(blob, parent,\nicElementId, parentContextDir)', 'start', 'Called from MainWindow::openICInTab after createNewTab()'],
        ['block',   'SimulationBlocker\n(pause simulation)',              'step',  'RAII guard: pauses simulation, resumes on scope exit'],
        ['d_dir',   'parentContextDir\nempty?',                           'decision', ''],
        ['skip_d',  'Skip\n(leave contextDir unchanged)', 'step',    'Relative IC paths inside the blob won\u2019t resolve'],
        ['set_dir', 'setContextDir\n(parentContextDir)',                  'step',  'Inherits parent\u2019s dir so nested IC files resolve'],
        ['preamble','readPreamble(stream)\n\u2192 version + metadata',   'key',   'Blob is a full .panda file: magic header, version, metadata'],
        ['blobs',   'deserializeBlobRegistry\n\u2192 setBlob(k, v)\nfor each nested blob', 'step', 'Extract nested embedded IC blobs from metadata into ICRegistry'],
        ['ctx',     'Build deserialization context:\nportMap + contextDir', 'step', ''],
        ['deser', 'Serialization::deserialize\n(stream, context) \u2192 items', 'key', 'Reconstructs all GraphicElements + QNEConnections from stream', 'ser_deserialize'],
        ['add',     'For each item:\nscene.addItem(item)\ntrack lastId',  'step',  ''],
        ['rect',    'setLastId + setSceneRect\n(itemsBoundingRect)',       'step',  ''],
        ['mark',    'm_isInlineIC = true\nm_parentWorkspace = parent\nm_parentICElementId = id', 'key', ''],
        ['d_par',   'parent\nnot null?',                                   'decision', ''],
        ['no_name', 'blobName stays empty',                                'step',   ''],
        ['derive',  'Derive m_inlineBlobName\nfrom parent IC element',    'end',    'parent->scene()->itemById(id)->blobName()'],
      ],
  edges: [
        ['start',    'block'],
        ['block',    'd_dir'],
        ['d_dir',    'skip_d',   'Yes'],
        ['d_dir',    'set_dir',  'No'],
        ['skip_d',   'preamble'],
        ['set_dir',  'preamble'],
        ['preamble', 'blobs'],
        ['blobs',    'ctx'],
        ['ctx',      'deser'],
        ['deser',    'add'],
        ['add',      'rect'],
        ['rect',     'mark'],
        ['mark',     'd_par'],
        ['d_par',    'no_name',  'No'],
        ['d_par',    'derive',   'Yes'],
      ]
};

flowRegistry['ws_save_inline'] = {
  title: 'Save (inline IC tab)',
  nodes: [
        ['start',     'WorkSpace::save()\nCtrl+S in inline IC tab',       'start', ''],
        ['d_ver',     'isFromNewerVersion?',                               'decision', 'File was loaded from a newer wiRedPanda version'],
        ['w_ver',     'Warning:\n"Please update wiRedPanda"\nreturn',     'error',   'Saving would lose newer-format data'],
        ['d_inline',  'm_isInlineIC?',                                     'decision', ''],
        ['file_save', 'Standard save-to-disk\nflow (not covered here)',   'step',    ''],
        ['d_parent',  'm_parentWorkspace\nnot null?',                      'decision', 'Parent may have been closed while this inline tab was still open'],
        ['w_orphan',  'qCWarning: "parent closed"\nreturn (no-op)',       'error',   'Orphaned tab \u2014 save silently ignored'],
        ['auto_emb',  'Auto-embed file-backed ICs:\nFor each IC where !isEmbedded()', 'key', 'Ensures the blob is self-contained before propagating'],
        ['d_has',     'icRegistry\nhasBlob(baseName)?', 'decision', ''],
        ['d_fexist',  'File exists\nat contextDir?',    'decision', ''],
        ['d_fread',   'File\nreadable?',                'decision', ''],
        ['skip_f',    'skip\n(can\u2019t resolve)',     'error',   ''],
        ['reg_b',     'registerBlob(baseName,\nf.readAll())',             'step',  ''],
        ['set_bn',    'setBlobName + loadFromBlob\n(convert in-place)',   'step',  ''],
        ['ser', 'Serialize scene to QByteArray:\nwritePandaHeader\nserializeBlobRegistry\nserialize(scene.items())', 'key', 'Full .panda format blob', 'ser_header'],
        ['clean',     'undoStack->setClean()',                             'step',  'Tab title loses the * unsaved marker'],
        ['emit_sig', 'emit icBlobSaved\n(parentICElementId, blob)', 'end', 'Connected to parent->onChildICBlobSaved', 'ws_child_blob'],
      ],
  edges: [
        ['start',    'd_ver'],
        ['d_ver',    'w_ver',     'Yes'],
        ['d_ver',    'd_inline',  'No'],
        ['d_inline', 'file_save', 'No'],
        ['d_inline', 'd_parent',  'Yes'],
        ['d_parent', 'w_orphan',  'No'],
        ['d_parent', 'auto_emb',  'Yes'],
        ['auto_emb', 'd_has'],
        ['d_has',    'set_bn',    'Yes'],
        ['d_has',    'd_fexist',  'No'],
        ['d_fexist', 'skip_f',   'No'],
        ['d_fexist', 'd_fread',  'Yes'],
        ['d_fread',  'skip_f',   'No'],
        ['d_fread',  'reg_b',    'Yes'],
        ['reg_b',    'set_bn'],
        ['set_bn',   'ser'],
        ['ser',      'clean'],
        ['clean',    'emit_sig'],
      ]
};

flowRegistry['ws_child_blob'] = {
  title: 'onChildICBlobSaved',
  nodes: [
        ['start',    'onChildICBlobSaved\n(icElementId, blob)',            'start', 'Triggered when child inline IC tab emits icBlobSaved'],
        ['find',     'scene->itemById(icElementId)',                       'step',  ''],
        ['d_found',  'Item found?',                                        'decision', ''],
        ['r_orph',   'return\n(orphaned child tab)',                       'error', 'IC was deleted or undone in parent scene while child tab was open'],
        ['d_emb',    'Element is\nembedded?',                              'decision', 'dynamic_cast<GraphicElement*> && isEmbedded()'],
        ['r_ext',    'return\n(was extracted to file)',                    'error', 'Element was converted to file-backed while child tab was open'],
        ['targets',  'findICsByBlobName\n(elm->blobName()) \u2192 targets', 'step', 'All IC instances sharing this blob name in parent scene'],
        ['d_tgt',    'targets\nempty?',                                    'decision', ''],
        ['r_none',   'return',                                             'error', 'No instances to update'],
        ['capture',  'captureConnections(targets)',                        'step',  ''],
        ['block',    'SimulationBlocker\n(pause simulation)',              'step',  ''],
        ['snap',     'oldData = captureSnapshot\noldBlob = registry blob', 'step', 'Full undo state captured before mutation'],
        ['setblob',  'icRegistry->setBlob\n(blobName, blob)',             'key',   'Replace blob bytes in the registry'],
        ['loop', 'For each IC target:\nic->loadFromBlob(blob, dir)', 'key', 'Rebuild internal elements from new blob bytes', 'ws_load_blob'],
        ['d_ex',     'Exception\nthrown?',                                 'decision', ''],
        ['rollback', 'rollbackElements(updated, oldData)\nsetBlob(blobName, oldBlob)\nre-throw', 'error', 'Restore both elements and registry to pre-update state'],
        ['cmd', 'UpdateBlobCommand(setOldBlob)\n\u2192 undoStack->push', 'end', 'Undo: restore old blob + old elements. Redo: re-apply new blob.', 'cmd_update'],
      ],
  edges: [
        ['start',    'find'],
        ['find',     'd_found'],
        ['d_found',  'r_orph',   'No'],
        ['d_found',  'd_emb',    'Yes'],
        ['d_emb',    'r_ext',    'No'],
        ['d_emb',    'targets',  'Yes'],
        ['targets',  'd_tgt'],
        ['d_tgt',    'r_none',   'Yes'],
        ['d_tgt',    'capture',  'No'],
        ['capture',  'block'],
        ['block',    'snap'],
        ['snap',     'setblob'],
        ['setblob',  'loop'],
        ['loop',     'd_ex'],
        ['d_ex',     'rollback', 'Yes'],
        ['d_ex',     'cmd',      'No'],
      ]
};

flowRegistry['ws_save_disk'] = {
  title: 'save() to Disk',
  nodes: [
        ['start',    'WorkSpace::save(fileName)\n(normal file path)',  'start', 'Not the inline IC path \u2014 this is save-to-disk'],
        ['d_ver',    'isFromNewerVersion?',                             'decision',''],
        ['w_ver',    'Warning:\n"Please update wiRedPanda"\nreturn',   'error',  'Saving would lose newer-format data'],
        ['d_fn',     'fileName empty\nor autosave path?',               'decision',''],
        ['prompt',   'FileDialog::getSaveFileName',                     'step',   'Prompt for a real save path'],
        ['d_prompt', 'fileName\nempty?',                                'decision','User cancelled'],
        ['r_cancel', 'return',                                          'error',  ''],
        ['suffix',   'Append ".panda" if missing',                      'step',   ''],
        ['copy_dep', 'Copy external file deps\nto new directory',       'step',   'Appearances, audio, IC sub-circuits, .dolphin files. Only if contextDir changed.'],
        ['set_file', 'setCurrentFile(fileName)',                        'step',   'm_fileInfo = QFileInfo(fileName); scene.setContextDir(dir)'],
        ['savefile', 'QSaveFile::open(WriteOnly)',                      'step',   ''],
        ['d_open',   'Open\nsucceeded?',                                'decision',''],
        ['ex_open',  'throw PANDACEPTION\n"Error opening file"',       'error',  ''],
        ['rect',     'Tighten scene rect\n(itemsBounds + viewport)',    'step',   'Avoids viewport jump on element selection'],
        ['header',   'writePandaHeader(stream)',                        'step',   '', 'ser_header'],
        ['save_s', 'save(stream)', 'key', 'Writes metadata (dolphin, port metadata, blob registry, fileBackedICs) then serialize(items)', 'ser_serialize'],
        ['d_commit', 'saveFile.commit()\nsucceeded?',                   'decision','Atomic rename: temp \u2192 final'],
        ['ex_comm',  'throw PANDACEPTION\n"Could not save file"',      'error',  ''],
        ['clean',    'undoStack->setClean()',                            'step',   'Tab title loses the * marker'],
        ['autoclean','Clean up autosave records',                       'step',   'Remove recovered + autosave file entries from Settings'],
        ['done',     'emit fileChanged(m_fileInfo)',                     'end',    ''],
      ],
  edges: [
        ['start',    'd_ver'],
        ['d_ver',    'w_ver',     'Yes'],
        ['d_ver',    'd_fn',      'No'],
        ['d_fn',     'prompt',    'Yes'],
        ['d_fn',     'suffix',    'No'],
        ['prompt',   'd_prompt'],
        ['d_prompt', 'r_cancel',  'Yes'],
        ['d_prompt', 'suffix',    'No'],
        ['suffix',   'copy_dep'],
        ['copy_dep', 'set_file'],
        ['set_file', 'savefile'],
        ['savefile', 'd_open'],
        ['d_open',   'ex_open',   'No'],
        ['d_open',   'rect',      'Yes'],
        ['rect',     'header'],
        ['header',   'save_s'],
        ['save_s',   'd_commit'],
        ['d_commit', 'ex_comm',   'No'],
        ['d_commit', 'clean',     'Yes'],
        ['clean',    'autoclean'],
        ['autoclean','done'],
      ]
};

flowRegistry['ws_load_file'] = {
  title: 'load() from File',
  nodes: [
        ['start',    'WorkSpace::load(fileName)',                       'start', ''],
        ['d_exist',  'File exists?',                                    'decision',''],
        ['ex_exist', 'throw PANDACEPTION\n"File does not exist"',      'error',  ''],
        ['set_file', 'setCurrentFile(fileName)',                        'step',   ''],
        ['d_open',   'File readable?',                                  'decision',''],
        ['ex_open',  'throw PANDACEPTION\n"Could not open file"',      'error',  ''],
        ['header',   'readPandaHeader(stream)\n\u2192 version',        'key',    '', 'ser_header'],
        ['d_migrate','version < current\n&& migration enabled?',       'decision',''],
        ['backup',   'createVersionedBackup\n(fileName, version)',     'step',   'Save copy as .vX.Y.panda before upgrading'],
        ['load_s',   'load(stream, version, dir)',                      'key',    'Inner method with SimulationBlocker'],
        ['block',    'SimulationBlocker\npause simulation',            'step',   ''],
        ['d_newer',  'version > current?',                              'decision','Interactive mode only'],
        ['w_newer',  'Warning:\n"Newer version file.\nSaving blocked."','step',  ''],
        ['d_older',  'version < current?',                              'decision','Interactive mode only'],
        ['i_older',  'Info:\n"File upgraded.\nBackup created."',       'step',   ''],
        ['meta',     'Read metadata:\ndolphin, blob registry',         'step',   'V4.6+: unified map. Older: positional fields + optional map.'],
        ['blobs',    'Populate ICRegistry\nwith embedded blobs',       'step',   ''],
        ['ctx',      'Build deserialization\ncontext + portMap',        'step',   ''],
        ['deser', 'Serialization::deserialize\n(stream, context)', 'key', '', 'ser_deserialize'],
        ['add',      'addItem() for each\ntrack lastId',               'step',   ''],
        ['rect',     'setLastId + setSceneRect',                        'step',   ''],
        ['close',    'file.close()',                                     'step',   ''],
        ['d_resave', 'needsMigration?',                                 'decision','Re-save in new format after successful load'],
        ['resave',   'save(fileName)',                                   'step',   'Write upgraded file to disk'],
        ['done',     'emit fileChanged',                                 'end',    ''],
      ],
  edges: [
        ['start',    'd_exist'],
        ['d_exist',  'ex_exist',  'No'],
        ['d_exist',  'set_file',  'Yes'],
        ['set_file', 'd_open'],
        ['d_open',   'ex_open',   'No'],
        ['d_open',   'header',    'Yes'],
        ['header',   'd_migrate'],
        ['d_migrate','backup',    'Yes'],
        ['d_migrate','load_s',    'No'],
        ['backup',   'load_s'],
        ['load_s',   'block'],
        ['block',    'd_newer'],
        ['d_newer',  'w_newer',   'Yes'],
        ['d_newer',  'd_older',   'No'],
        ['w_newer',  'meta'],
        ['d_older',  'i_older',   'Yes'],
        ['d_older',  'meta',      'No'],
        ['i_older',  'meta'],
        ['meta',     'blobs'],
        ['blobs',    'ctx'],
        ['ctx',      'deser'],
        ['deser',    'add'],
        ['add',      'rect'],
        ['rect',     'close'],
        ['close',    'd_resave'],
        ['d_resave', 'resave',    'Yes'],
        ['d_resave', 'done',      'No'],
        ['resave',   'done'],
      ]
};

flowRegistry['ws_autosave'] = {
  title: 'autosave()',
  nodes: [
        ['start',    'WorkSpace::autosave()',                          'start', 'Called periodically by QTimer'],
        ['d_inline', 'm_isInlineIC?',                                  'decision','Inline IC tabs don\u2019t autosave to disk'],
        ['r_inline', 'return',                                          'error',  ''],
        ['d_ver',    'isFromNewerVersion?',                             'decision',''],
        ['r_ver',    'return',                                          'error',  'Autosaving would lose newer-format data'],
        ['d_clean',  'undoStack\nisClean?',                             'decision','No unsaved changes'],
        ['rm_old',   'Remove old autosave\nfile + emit fileChanged',   'end',    ''],
        ['d_path',   'fileInfo.fileName\nempty?',                       'decision','New unsaved project vs existing file'],
        ['path_new', 'autosavePath =\nglobal AppData/autosaves',       'step',   'Leading dot makes it hidden on Unix. XXXXXX for unique suffix.'],
        ['d_writable','File directory\nwritable?',                      'decision',''],
        ['path_dir', 'autosavePath =\nfile\u2019s directory',          'step',   ''],
        ['path_ro',  'autosavePath =\nglobal AppData/autosaves',       'step',   'File dir is read-only (e.g. AppImage)'],
        ['d_open',   'autosaveFile\nopened?',                           'decision',''],
        ['ex_open',  'throw PANDACEPTION\n"Error opening autosave"',   'error',  ''],
        ['write', 'writePandaHeader +\nsave(stream)', 'key', 'Full .panda format to temp file', 'ser_header'],
        ['close',    'autosaveFile.close()',                            'step',   ''],
        ['reg',      'Register in Settings\nautosaveFiles list',       'step',   ''],
        ['done',     'emit fileChanged',                                'end',    ''],
      ],
  edges: [
        ['start',     'd_inline'],
        ['d_inline',  'r_inline',   'Yes'],
        ['d_inline',  'd_ver',      'No'],
        ['d_ver',     'r_ver',      'Yes'],
        ['d_ver',     'd_clean',    'No'],
        ['d_clean',   'rm_old',     'Yes'],
        ['d_clean',   'd_path',     'No'],
        ['d_path',    'path_new',   'Yes'],
        ['d_path',    'd_writable', 'No'],
        ['d_writable','path_dir',   'Yes'],
        ['d_writable','path_ro',    'No'],
        ['path_new',  'd_open'],
        ['path_dir',  'd_open'],
        ['path_ro',   'd_open'],
        ['d_open',    'ex_open',    'No'],
        ['d_open',    'write',      'Yes'],
        ['write',     'close'],
        ['close',     'reg'],
        ['reg',       'done'],
      ]
};

