// Flow definitions: workspace
flowRegistry['ws_ops'] = {
  title: 'Workspace \u2014 Per-Tab Environment',
  nodes: [
    ['root',    'Workspace',                         'start', 'One per open circuit tab: Scene + View + Simulation'],
    ['file_io', 'File I/O',                          'step',  ''],
    ['save',    'Save to Disk',                      'key',   'Atomic file write, autosave cleanup', 'ws_save_disk'],
    ['load',    'Load from File',                    'key',   'Read header, migration, deserialize', 'ws_load_file'],
    ['autosave','Autosave',                          'key',   'Periodic temp file, settings registry', 'ws_autosave'],
    ['inline',  'Inline IC Tab',                     'step',  ''],
    ['blob_l',  'Load from Blob',                    'key',   'Deserialize embedded IC into child tab', 'ws_load_blob'],
    ['blob_s',  'Save as Blob',                      'key',   'Serialize \u2192 notify parent of blob update', 'ws_save_inline'],
    ['child',   'Receive Child\nBlob Update',       'key',   'Atomic reload of all instances sharing the blob', 'ws_child_blob'],
  ],
  edges: [
    ['root',    'file_io'],
    ['root',    'inline'],
    ['file_io', 'save'],
    ['file_io', 'load'],
    ['file_io', 'autosave'],
    ['inline',  'blob_l'],
    ['inline',  'blob_s'],
    ['blob_s',  'child'],
  ]
};

flowRegistry['ws_load_blob'] = {
  title: 'Load from Blob',
  nodes: [
        ['start',   'Load from blob\n(parent, IC element ID,\nparent directory)', 'start', 'Called after creating a new tab for inline IC'],
        ['block',   'Pause simulation',                                   'step',  'RAII guard: pauses simulation, resumes on scope exit'],
        ['d_dir',   'Parent directory\nprovided?',                         'decision', ''],
        ['skip_d',  'Skip\n(leave directory unchanged)', 'step',    'Relative IC paths inside the blob won\u2019t resolve'],
        ['set_dir', 'Set working directory\nfrom parent',                  'step',  'Inherits parent\u2019s dir so nested IC files resolve'],
        ['preamble','Read preamble\n(version + metadata)',                 'key',   'Blob is a full .panda file: magic header, version, metadata'],
        ['blobs',   'Extract nested\nembedded IC blobs\nfrom metadata',   'step', ''],
        ['ctx',     'Build deserialization\ncontext',                      'step', ''],
        ['deser', 'Deserialize elements\nand connections', 'key', 'Reconstructs all elements and wires from stream', 'ser_deserialize'],
        ['add',     'Add items to scene\nand track IDs',                   'step',  ''],
        ['rect',    'Set scene bounds',                                    'step',  ''],
        ['mark',    'Mark as inline IC tab\nand link to parent',           'key',   ''],
        ['d_par',   'Parent\nprovided?',                                   'decision', ''],
        ['no_name', 'Blob name\nstays empty',                             'step',   ''],
        ['derive',  'Derive blob name\nfrom parent IC element',           'end',    ''],
      ],
  edges: [
        ['start',    'block'],
        ['block',    'd_dir'],
        ['d_dir',    'skip_d',   'No'],
        ['d_dir',    'set_dir',  'Yes'],
        ['skip_d',   'preamble'],
        ['set_dir',  'preamble'],
        ['preamble', 'blobs'],
        ['blobs',    'ctx'],
        ['ctx',      'deser'],
        ['deser',    'add'],
        ['add',      'rect'],
        ['rect',     'mark'],
        ['mark',     'd_par'],
        ['d_par',    'no_name',  'No'],
        ['d_par',    'derive',   'Yes'],
      ]
};

flowRegistry['ws_save_inline'] = {
  title: 'Save (inline IC tab)',
  nodes: [
        ['start',     'Ctrl+S in\ninline IC tab',                         'start', ''],
        ['d_ver',     'From newer\nversion?',                              'decision', 'File was loaded from a newer wiRedPanda version'],
        ['w_ver',     'Warning:\n"Please update\nwiRedPanda"',            'error',   'Saving would lose newer-format data'],
        ['d_inline',  'Inline IC tab?',                                    'decision', ''],
        ['file_save', 'Standard save-to-disk\n(not covered here)',        'step',    ''],
        ['d_parent',  'Parent workspace\nstill open?',                     'decision', 'Parent may have been closed while this inline tab was still open'],
        ['w_orphan',  'Warning:\n"Parent closed"\n(no-op)',               'error',   'Orphaned tab \u2014 save silently ignored'],
        ['auto_emb',  'Auto-embed file-backed\nICs in this scene',        'key', 'Ensures the blob is self-contained before propagating'],
        ['d_has',     'Blob already\nregistered?',                         'decision', ''],
        ['d_fexist',  'File exists?',                                      'decision', ''],
        ['d_fread',   'File\nreadable?',                                   'decision', ''],
        ['skip_f',    'Skip\n(can\u2019t resolve)',                        'error',   ''],
        ['reg_b',     'Register file as blob',                             'step',  ''],
        ['set_bn',    'Convert IC in-place\n(set blob, reload)',           'step',  ''],
        ['ser', 'Serialize scene\nto blob data', 'key', 'Full .panda format: header + metadata + elements', 'ser_header'],
        ['clean',     'Mark undo stack\nas clean',                         'step',  'Tab title loses the * unsaved marker'],
        ['emit_sig', 'Notify parent of\nblob update', 'end', 'Connected to parent workspace', 'ws_child_blob'],
      ],
  edges: [
        ['start',    'd_ver'],
        ['d_ver',    'w_ver',     'Yes'],
        ['d_ver',    'd_inline',  'No'],
        ['d_inline', 'file_save', 'No'],
        ['d_inline', 'd_parent',  'Yes'],
        ['d_parent', 'w_orphan',  'No'],
        ['d_parent', 'auto_emb',  'Yes'],
        ['auto_emb', 'd_has'],
        ['d_has',    'set_bn',    'Yes'],
        ['d_has',    'd_fexist',  'No'],
        ['d_fexist', 'skip_f',   'No'],
        ['d_fexist', 'd_fread',  'Yes'],
        ['d_fread',  'skip_f',   'No'],
        ['d_fread',  'reg_b',    'Yes'],
        ['reg_b',    'set_bn'],
        ['set_bn',   'ser'],
        ['ser',      'clean'],
        ['clean',    'emit_sig'],
      ]
};

flowRegistry['ws_child_blob'] = {
  title: 'Receive Child Blob Update',
  nodes: [
        ['start',    'Child inline IC tab\nsaved a blob update',          'start', ''],
        ['find',     'Find IC element\nby ID in scene',                    'step',  ''],
        ['d_found',  'Element\nfound?',                                    'decision', ''],
        ['r_orph',   'Abort\n(orphaned child tab)',                        'error', 'IC was deleted or undone in parent scene'],
        ['d_emb',    'Element is\nembedded?',                              'decision', ''],
        ['r_ext',    'Abort\n(was extracted to file)',                     'error', 'Element was converted to file-backed while child tab was open'],
        ['targets',  'Find all IC instances\nsharing this blob name',      'step', ''],
        ['d_tgt',    'Instances\nfound?',                                  'decision', ''],
        ['r_none',   'Abort',                                              'error', 'No instances to update'],
        ['capture',  'Snapshot connections',                               'step',  ''],
        ['block',    'Pause simulation',                                   'step',  ''],
        ['snap',     'Snapshot element state\nand current blob',           'step', 'Full undo state captured before mutation'],
        ['setblob',  'Update blob\nin registry',                           'key',   'Replace blob bytes'],
        ['loop', 'For each IC instance:\nreload from new blob', 'key', 'Rebuild internal elements from new blob bytes', 'ws_load_blob'],
        ['d_ex',     'Error during\nreload?',                              'decision', ''],
        ['rollback', 'Rollback:\nrestore elements\nand blob, re-throw',   'error', 'Restore both elements and registry to pre-update state'],
        ['cmd', 'Push undo command', 'end', 'Undo: restore old blob + old elements. Redo: re-apply new blob.', 'cmd_update'],
      ],
  edges: [
        ['start',    'find'],
        ['find',     'd_found'],
        ['d_found',  'r_orph',   'No'],
        ['d_found',  'd_emb',    'Yes'],
        ['d_emb',    'r_ext',    'No'],
        ['d_emb',    'targets',  'Yes'],
        ['targets',  'd_tgt'],
        ['d_tgt',    'r_none',   'No'],
        ['d_tgt',    'capture',  'Yes'],
        ['capture',  'block'],
        ['block',    'snap'],
        ['snap',     'setblob'],
        ['setblob',  'loop'],
        ['loop',     'd_ex'],
        ['d_ex',     'rollback', 'Yes'],
        ['d_ex',     'cmd',      'No'],
      ]
};

flowRegistry['ws_save_disk'] = {
  title: 'Save to Disk',
  nodes: [
        ['start',    'Save to file',                                'start', 'Not the inline IC path \u2014 this is save-to-disk'],
        ['d_ver',    'From newer\nversion?',                        'decision',''],
        ['w_ver',    'Warning:\n"Please update\nwiRedPanda"',      'error',  'Saving would lose newer-format data'],
        ['d_fn',     'File path empty\nor autosave path?',          'decision',''],
        ['prompt',   'Save file dialog',                            'step',   'Prompt for a real save path'],
        ['d_prompt', 'File path\nchosen?',                          'decision','User may cancel'],
        ['r_cancel', 'Abort',                                       'error',  ''],
        ['suffix',   'Append ".panda"\nif missing',                 'step',   ''],
        ['copy_dep', 'Copy external file deps\nto new directory',   'step',   'IC sub-circuits, .dolphin files, etc. Only if directory changed.'],
        ['set_file', 'Set current file path\nand working directory','step',   ''],
        ['savefile', 'Open file for writing\n(atomic)',             'step',   ''],
        ['d_open',   'Open\nsucceeded?',                            'decision',''],
        ['ex_open',  'Error:\n"Cannot open file"',                 'error',  ''],
        ['rect',     'Tighten scene bounds',                        'step',   'Avoids viewport jump on element selection'],
        ['header',   'Write file header',                           'step',   '', 'ser_header'],
        ['save_s', 'Write metadata\nand serialize items', 'key', 'Writes dolphin, port metadata, blob registry, file-backed ICs, then elements', 'ser_serialize'],
        ['d_commit', 'File commit\nsucceeded?',                     'decision','Atomic rename: temp \u2192 final'],
        ['ex_comm',  'Error:\n"Cannot save file"',                 'error',  ''],
        ['clean',    'Mark undo stack\nas clean',                   'step',   'Tab title loses the * marker'],
        ['autoclean','Clean up autosave\nrecords',                  'step',   'Remove recovered + autosave file entries'],
        ['done',     'Notify file changed',                         'end',    ''],
      ],
  edges: [
        ['start',    'd_ver'],
        ['d_ver',    'w_ver',     'Yes'],
        ['d_ver',    'd_fn',      'No'],
        ['d_fn',     'prompt',    'Yes'],
        ['d_fn',     'suffix',    'No'],
        ['prompt',   'd_prompt'],
        ['d_prompt', 'r_cancel',  'No'],
        ['d_prompt', 'suffix',    'Yes'],
        ['suffix',   'copy_dep'],
        ['copy_dep', 'set_file'],
        ['set_file', 'savefile'],
        ['savefile', 'd_open'],
        ['d_open',   'ex_open',   'No'],
        ['d_open',   'rect',      'Yes'],
        ['rect',     'header'],
        ['header',   'save_s'],
        ['save_s',   'd_commit'],
        ['d_commit', 'ex_comm',   'No'],
        ['d_commit', 'clean',     'Yes'],
        ['clean',    'autoclean'],
        ['autoclean','done'],
      ]
};

flowRegistry['ws_load_file'] = {
  title: 'Load from File',
  nodes: [
        ['start',    'Load from file',                              'start', ''],
        ['d_exist',  'File exists?',                                'decision',''],
        ['ex_exist', 'Error:\n"File does not exist"',              'error',  ''],
        ['set_file', 'Set current file path',                       'step',   ''],
        ['d_open',   'File readable?',                              'decision',''],
        ['ex_open',  'Error:\n"Cannot open file"',                 'error',  ''],
        ['header',   'Read file header\n\u2192 version',           'key',    '', 'ser_header'],
        ['d_migrate','Older version and\nmigration enabled?',       'decision',''],
        ['backup',   'Create versioned\nbackup',                   'step',   'Save copy as .vX.Y.panda before upgrading'],
        ['load_s',   'Load with\nsimulation paused',                'key',    ''],
        ['block',    'Pause simulation',                            'step',   ''],
        ['d_newer',  'Newer version\nthan app?',                    'decision',''],
        ['w_newer',  'Warning:\n"Newer version file.\nSaving blocked."','step',  ''],
        ['d_older',  'Older version\nthan app?',                    'decision',''],
        ['i_older',  'Info:\n"File upgraded.\nBackup created."',   'step',   ''],
        ['meta',     'Read metadata:\nwaveform file,\nblob registry', 'step', ''],
        ['blobs',    'Populate IC Registry\nwith embedded blobs',   'step',   ''],
        ['ctx',      'Build deserialization\ncontext',              'step',   ''],
        ['deser', 'Deserialize elements\nand connections', 'key', '', 'ser_deserialize'],
        ['add',      'Add items to scene\nand track IDs',           'step',   ''],
        ['rect',     'Set scene bounds\nand last ID',               'step',   ''],
        ['close',    'Close file',                                   'step',   ''],
        ['d_resave', 'Needs migration\nre-save?',                   'decision','Re-save in new format after successful load'],
        ['resave',   'Save upgraded file',                           'step',   'Write to disk in new format'],
        ['done',     'Notify file changed',                          'end',    ''],
      ],
  edges: [
        ['start',    'd_exist'],
        ['d_exist',  'ex_exist',  'No'],
        ['d_exist',  'set_file',  'Yes'],
        ['set_file', 'd_open'],
        ['d_open',   'ex_open',   'No'],
        ['d_open',   'header',    'Yes'],
        ['header',   'd_migrate'],
        ['d_migrate','backup',    'Yes'],
        ['d_migrate','load_s',    'No'],
        ['backup',   'load_s'],
        ['load_s',   'block'],
        ['block',    'd_newer'],
        ['d_newer',  'w_newer',   'Yes'],
        ['d_newer',  'd_older',   'No'],
        ['w_newer',  'meta'],
        ['d_older',  'i_older',   'Yes'],
        ['d_older',  'meta',      'No'],
        ['i_older',  'meta'],
        ['meta',     'blobs'],
        ['blobs',    'ctx'],
        ['ctx',      'deser'],
        ['deser',    'add'],
        ['add',      'rect'],
        ['rect',     'close'],
        ['close',    'd_resave'],
        ['d_resave', 'resave',    'Yes'],
        ['d_resave', 'done',      'No'],
        ['resave',   'done'],
      ]
};

flowRegistry['ws_autosave'] = {
  title: 'Autosave',
  nodes: [
        ['start',    'Autosave\n(periodic timer)',                 'start', ''],
        ['d_inline', 'Inline IC tab?',                              'decision','Inline IC tabs don\u2019t autosave to disk'],
        ['r_inline', 'Skip',                                        'error',  ''],
        ['d_ver',    'From newer\nversion?',                        'decision',''],
        ['r_ver',    'Skip',                                        'error',  'Autosaving would lose newer-format data'],
        ['d_clean',  'Unsaved\nchanges?',                           'decision',''],
        ['rm_old',   'Remove old autosave\nfile, notify',          'end',    ''],
        ['d_path',   'Project has\na file path?',                   'decision','New unsaved project vs existing file'],
        ['path_new', 'Use global\nautosave directory',             'step',   ''],
        ['d_writable','File directory\nwritable?',                  'decision',''],
        ['path_dir', 'Use file\u2019s\ndirectory',                 'step',   ''],
        ['path_ro',  'Use global\nautosave directory',             'step',   'File dir is read-only'],
        ['d_open',   'Autosave file\nopened?',                      'decision',''],
        ['ex_open',  'Error:\n"Cannot open autosave"',             'error',  ''],
        ['write', 'Write header\nand serialize scene', 'key', 'Full .panda format to temp file', 'ser_header'],
        ['close',    'Close autosave file',                         'step',   ''],
        ['reg',      'Register in settings\nautosave list',        'step',   ''],
        ['done',     'Notify file changed',                         'end',    ''],
      ],
  edges: [
        ['start',     'd_inline'],
        ['d_inline',  'r_inline',   'Yes'],
        ['d_inline',  'd_ver',      'No'],
        ['d_ver',     'r_ver',      'Yes'],
        ['d_ver',     'd_clean',    'No'],
        ['d_clean',   'rm_old',     'No'],
        ['d_clean',   'd_path',     'Yes'],
        ['d_path',    'path_new',   'No'],
        ['d_path',    'd_writable', 'Yes'],
        ['d_writable','path_dir',   'Yes'],
        ['d_writable','path_ro',    'No'],
        ['path_new',  'd_open'],
        ['path_dir',  'd_open'],
        ['path_ro',   'd_open'],
        ['d_open',    'ex_open',    'No'],
        ['d_open',    'write',      'Yes'],
        ['write',     'close'],
        ['close',     'reg'],
        ['reg',       'done'],
      ]
};
