set(SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphinUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/CodeGen/ArduinoCodeGen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Application.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Common.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Enums.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ItemWithId.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Settings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ThemeManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementLabel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/And.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/AudioBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Buzzer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Clock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Demux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display14.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display7.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputButton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputGND.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputRotary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputSwitch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputVCC.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/JKFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Led.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Line.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Mux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Text.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TruthTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xnor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/IC.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicAnd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDemux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicInput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicJKFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicMux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicOr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicOutput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTruthTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXnor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/RecentFiles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/Serialization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEConnection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEPort.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Commands.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/GraphicsView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Scene.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Workspace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/ElementMapping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/Simulation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/SimulationBlocker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialogUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditorUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LabeledSlider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialogUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindowUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/TrashButton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/HandlerFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPValidator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/StandardValidator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/BaseHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ConnectionHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ElementHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/FileHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/MCPUtilities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ServerInfoHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/SimulationHandler.cpp
)

set(HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphin.h
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphinUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/CodeGen/ArduinoCodeGen.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Application.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Common.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Enums.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ItemWithId.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Settings.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ThemeManager.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementFactory.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementLabel.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElement.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElementInput.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/And.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/AudioBox.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Buzzer.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Clock.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Demux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display14.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display16.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display7.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputButton.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputGND.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputRotary.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputSwitch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputVCC.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/JKFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Led.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Line.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Mux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nand.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Node.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Not.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Or.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Text.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TruthTable.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xnor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/IC.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElement.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicAnd.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDemux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicInput.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicJKFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicMux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNand.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNode.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNone.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNot.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicOr.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicOutput.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTruthTable.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXnor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/GlobalProperties.h
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/RecentFiles.h
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/Serialization.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEConnection.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEPort.h
    ${CMAKE_CURRENT_LIST_DIR}/App/RegisterTypes.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Commands.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/GraphicsView.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Scene.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Workspace.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/ElementMapping.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/Simulation.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/SimulationBlocker.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialogUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditorUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LabeledSlider.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialogUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindowUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/TrashButton.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/HandlerFactory.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPProcessor.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPValidator.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/StandardValidator.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/BaseHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ConnectionHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ElementHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/FileHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/MCPUtilities.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ServerInfoHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/SimulationHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Interfaces/ICommand.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Interfaces/IResponse.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Interfaces/IValidator.h
)

set(RESOURCES
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Assets/Assets.qrc
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Components/Components.qrc
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Interface/Interface.qrc
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Translations/Translations.qrc
)
