set(SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphinUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/Serializer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/SignalDelegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/SignalModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/WaveformView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/CodeGen/ArduinoCodeGen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/CodeGen/SystemVerilogCodeGen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Application.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Common.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Enums.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ItemWithId.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Settings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/SystemThemeDetector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ThemeManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/UpdateChecker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementLabel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementMetadata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/And.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/AudioBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Buzzer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Clock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Demux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display14.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display7.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputButton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputGND.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputRotary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputSwitch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputVCC.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/JKFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Led.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Line.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Mux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Text.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TruthTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xnor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/IC.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicAnd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDemux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicElement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicJKFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicMux.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicOr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTruthTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXnor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/RecentFiles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/Serialization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEConnection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEPort.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Commands.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/GraphicsView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Scene.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Workspace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/ElementMapping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/Simulation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/SimulationBlocker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/CircuitExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialogUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementContextMenu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementPalette.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LanguageManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditorUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementTabNavigator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LabeledSlider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialogUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindowUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/SelectionCapabilities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/TrashButton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/HandlerFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPValidator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/StandardValidator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/BaseHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ConnectionHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ElementHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/FileHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/MCPUtilities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ServerInfoHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/SimulationHandler.cpp
)

set(HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphin.h
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/BeWavedDolphinUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/Serializer.h
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/SignalDelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/SignalModel.h
    ${CMAKE_CURRENT_LIST_DIR}/App/BeWavedDolphin/WaveformView.h
    ${CMAKE_CURRENT_LIST_DIR}/App/CodeGen/ArduinoCodeGen.h
    ${CMAKE_CURRENT_LIST_DIR}/App/CodeGen/SystemVerilogCodeGen.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Application.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Common.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Enums.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ItemWithId.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Priorities.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/Settings.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/SystemThemeDetector.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/ThemeManager.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Core/UpdateChecker.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementFactory.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementInfo.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementLabel.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/ElementMetadata.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElement.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElementInput.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/And.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/AudioBox.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Buzzer.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Clock.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Demux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display14.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display16.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Display7.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/DLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputButton.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputGND.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputRotary.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputSwitch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/InputVCC.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/JKFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Led.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Line.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Mux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nand.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Node.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Nor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Not.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Or.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/SRLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Text.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/TruthTable.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xnor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/GraphicElements/Xor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/PropertyDescriptor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/IC.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicAnd.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDemux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicDLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicElement.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicJKFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicMux.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNand.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNode.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicNot.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicOr.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSink.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSource.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicSRLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicTruthTable.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXnor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Element/LogicElements/LogicXor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Versions.h
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/RecentFiles.h
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/Serialization.h
    ${CMAKE_CURRENT_LIST_DIR}/App/IO/SerializationContext.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEConnection.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Nodes/QNEPort.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Commands.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/GraphicsView.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Scene.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Scene/Workspace.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/ElementMapping.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/Simulation.h
    ${CMAKE_CURRENT_LIST_DIR}/App/Simulation/SimulationBlocker.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/CircuitExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ClockDialogUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementContextMenu.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementPalette.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LanguageManager.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditor.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementEditorUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/ElementTabNavigator.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LabeledSlider.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/LengthDialogUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/MainWindowUI.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/SelectionCapabilities.h
    ${CMAKE_CURRENT_LIST_DIR}/App/UI/TrashButton.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/HandlerFactory.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPProcessor.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/MCPValidator.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Core/StandardValidator.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/BaseHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ConnectionHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ElementHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/FileHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/MCPUtilities.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/ServerInfoHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Handlers/SimulationHandler.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Interfaces/ICommand.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Interfaces/IResponse.h
    ${CMAKE_CURRENT_LIST_DIR}/MCP/Server/Interfaces/IValidator.h
)

set(RESOURCES
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Assets/Assets.qrc
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Components/Components.qrc
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Interface/Interface.qrc
    ${CMAKE_CURRENT_LIST_DIR}/App/Resources/Translations/Translations.qrc
)

set(TEST_UTILS_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Common/TestUtils.cpp
)

set(TEST_UTILS_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Common/TestUtils.h
)

set(MEMORY_HELPERS_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/MemoryHelpers.cpp
)

set(MEMORY_HELPERS_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/MemoryHelpers.h
)

set(TEST_WIREDPANDA_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUAlu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUBranch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUControlUnit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUDecoders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUInstructionExecute.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUInstructionFetch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUIntegration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUMemoryInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUProgramCounter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPURegisterBank.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPURegisters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1DFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1DLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1JkFlipFlop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1SrLatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Decoder2to4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Decoder3to8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Decoder4to16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2FullAdder1bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2HalfAdder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Mux2to1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Mux4to1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Mux8to1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2ParityChecker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2ParityGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2PriorityEncoder8to3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2PriorityMux3to1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3AluSelector5way.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Bcd7segmentDecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Comparator4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Comparator4bitEquality.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Register1bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4BinaryCounter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4BusMux4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4BusMux8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Comparator4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4JohnsonCounter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Ram4x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Ram8x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Register4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4RingCounter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4RippleAdder4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4RippleAlu4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4ShiftRegisterPiso.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4ShiftRegisterSipo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5BarrelRotator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5BarrelShifter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5ClockGatedDecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5Controller4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5InstructionDecoder4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5LoadableCounter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5ModuloCounter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5ProgramCounter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5RegisterFile4x4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5RegisterFile8x8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6StackMemoryInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5UpDownCounter4bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6Alu8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6ProgramCounter8bitArithmetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6Ram256x8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6Register8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6RegisterFile8x8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6RippleAdder8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6StackPointer8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7Alu16bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7CpuProgramCounter8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7DataForwardingUnit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7ExecutionDatapath.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7FlagRegister.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7InstructionDecoder8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7InstructionMemoryInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7InstructionRegister8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8DecodeStage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8ExecuteStage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8FetchStage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8MemoryStage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9Cpu16bitRisc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9FetchStage16bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9MultiCycleCpu8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9SingleCycleCpu8bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestDecoder8to256.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestMemorySettlingTime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestRamCell1bit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestSequential.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/Logic/TestMuxDemuxComprehensive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestArduino.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestFeedback.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestFiles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestIc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestSimulation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestSystemVerilogExport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestWorkspace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestWorkspaceFileops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Resources/TestIcons.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Runners/TestWiredpanda.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/System/TestWaveform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Commands/TestCommands.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestCommon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestEnums.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestPriorities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestRecentFiles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestThemeManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestAudioBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestBuzzer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestClock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestClocksAdvanced.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestComponents.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestDisplays.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestElementLabel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestElementProperties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestFeatures.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestGeometry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestWirelessNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestGraphicelementAdvanced.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestInputElements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestInputRotary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestLed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestLogicGates.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestMultiplexing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestSequentialLogic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestTruthTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Factory/TestElementFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Logic/TestLogicElements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Logic/TestLogicElementsErrors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Logic/TestLogicNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Nodes/TestConnectionSerialization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Nodes/TestConnections.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestConnectionValidity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestScene.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestSceneConnections.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestSceneState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestSceneUndoredo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Serialization/TestSerialization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Simulation/TestElementMapping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Simulation/TestSimulationBlocker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Simulation/TestTemporalSimulation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Ui/TestDialogs.cpp
)

set(TEST_WIREDPANDA_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUAlu.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUBranch.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUControlUnit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUDecoders.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUInstructionExecute.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUInstructionFetch.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUIntegration.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUMemoryInterface.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPUProgramCounter.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPURegisterBank.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/Cpu/TestCPURegisters.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1DFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1DLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1JkFlipFlop.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel1SrLatch.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Decoder2to4.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Decoder3to8.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Decoder4to16.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2FullAdder1bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2HalfAdder.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Mux2to1.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Mux4to1.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2Mux8to1.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2ParityChecker.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2ParityGenerator.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2PriorityEncoder8to3.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel2PriorityMux3to1.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3AluSelector5way.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Bcd7segmentDecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Comparator4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Comparator4bitEquality.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel3Register1bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4BinaryCounter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4BusMux4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4BusMux8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Comparator4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4JohnsonCounter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Ram4x1.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Ram8x1.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4Register4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4RingCounter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4RippleAdder4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4RippleAlu4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4ShiftRegisterPiso.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel4ShiftRegisterSipo.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5BarrelRotator.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5BarrelShifter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5ClockGatedDecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5Controller4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5InstructionDecoder4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5LoadableCounter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5ModuloCounter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5ProgramCounter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5RegisterFile4x4.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5RegisterFile8x8.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6StackMemoryInterface.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel5UpDownCounter4bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6Alu8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6ProgramCounter8bitArithmetic.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6Ram256x8.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6Register8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6RegisterFile8x8.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6RippleAdder8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel6StackPointer8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7Alu16bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7CpuProgramCounter8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7DataForwardingUnit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7ExecutionDatapath.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7FlagRegister.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7InstructionDecoder8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7InstructionMemoryInterface.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel7InstructionRegister8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8DecodeStage.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8ExecuteStage.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8FetchStage.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel8MemoryStage.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9Cpu16bitRisc.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9FetchStage16bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9MultiCycleCpu8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestLevel9SingleCycleCpu8bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestDecoder8to256.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestMemorySettlingTime.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestRamCell1bit.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/IC/Tests/TestsWithoutPanda/TestSequential.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/Logic/TestMuxDemuxComprehensive.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestArduino.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestFeedback.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestFiles.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestIc.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestSimulation.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestSystemVerilogExport.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestWorkspace.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Integration/TestWorkspaceFileops.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Resources/TestIcons.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/System/TestWaveform.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Commands/TestCommands.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestCommon.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestEnums.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestPriorities.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestRecentFiles.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Common/TestThemeManager.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestAudioBox.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestBuzzer.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestClock.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestClocksAdvanced.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestComponents.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestDisplays.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestElementLabel.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestElementProperties.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestFeatures.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestGeometry.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestWirelessNode.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestGraphicelementAdvanced.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestInputElements.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestInputRotary.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestLed.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestLogicGates.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestMultiplexing.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestSequentialLogic.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Elements/TestTruthTable.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Factory/TestElementFactory.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Logic/TestLogicElements.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Logic/TestLogicElementsErrors.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Logic/TestLogicNode.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Nodes/TestConnectionSerialization.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Nodes/TestConnections.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestConnectionValidity.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestScene.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestSceneConnections.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestSceneState.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Scene/TestSceneUndoredo.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Serialization/TestSerialization.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Simulation/TestElementMapping.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Simulation/TestSimulationBlocker.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Simulation/TestTemporalSimulation.h
    ${CMAKE_CURRENT_LIST_DIR}/Tests/Unit/Ui/TestDialogs.h
)

