
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.11.0-1018-azure - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/FindThreads.cmake:99 (CHECK_CXX_SOURCE_COMPILES)"
      - "/usr/local/share/cmake-3.31/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Dependencies.cmake:34 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:162 (include)"
      - "CMakeLists.txt:17 (find_package)"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-Q1MZoa"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-Q1MZoa"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-Q1MZoa'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_2e5f3/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_2e5f3.dir/build.make CMakeFiles/cmTC_2e5f3.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-Q1MZoa'
        Building CXX object CMakeFiles/cmTC_2e5f3.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DCMAKE_HAVE_LIBC_PTHREAD  -std=c++20 -MD -MT CMakeFiles/cmTC_2e5f3.dir/src.cxx.o -MF CMakeFiles/cmTC_2e5f3.dir/src.cxx.o.d -o CMakeFiles/cmTC_2e5f3.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-Q1MZoa/src.cxx
        shared:INFO: (Emscripten: Running sanity checks)
        Linking CXX executable cmTC_2e5f3.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2e5f3.dir/link.txt --verbose=1
        cache:INFO: generating system asset: symbol_lists/dae99d994d603fb13aa7edd6245a890f9752f2c4.json... (this will be cached in "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cache/symbol_lists/dae99d994d603fb13aa7edd6245a890f9752f2c4.json" for subsequent builds)
        cache:INFO:  - ok
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_2e5f3.dir/objects1.rsp -o cmTC_2e5f3.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-Q1MZoa'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapAtomic.cmake:36 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_STDATOMIC"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-EBoodX"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-EBoodX"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_STDATOMIC"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-EBoodX'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_a100f/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_a100f.dir/build.make CMakeFiles/cmTC_a100f.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-EBoodX'
        Building CXX object CMakeFiles/cmTC_a100f.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_STDATOMIC  -std=c++20 -MD -MT CMakeFiles/cmTC_a100f.dir/src.cxx.o -MF CMakeFiles/cmTC_a100f.dir/src.cxx.o.d -o CMakeFiles/cmTC_a100f.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-EBoodX/src.cxx
        Linking CXX executable cmTC_a100f.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a100f.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_a100f.dir/objects1.rsp -o cmTC_a100f.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-EBoodX'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:23 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_GETTIME"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-WntNvn"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-WntNvn"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_GETTIME"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-WntNvn'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_094a3/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_094a3.dir/build.make CMakeFiles/cmTC_094a3.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-WntNvn'
        Building CXX object CMakeFiles/cmTC_094a3.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_GETTIME  -std=c++20 -MD -MT CMakeFiles/cmTC_094a3.dir/src.cxx.o -MF CMakeFiles/cmTC_094a3.dir/src.cxx.o.d -o CMakeFiles/cmTC_094a3.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-WntNvn/src.cxx
        Linking CXX executable cmTC_094a3.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_094a3.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_094a3.dir/objects1.rsp -o cmTC_094a3.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-WntNvn'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:34 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_SHM_OPEN_SHM_UNLINK"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-KswfNb"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-KswfNb"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_SHM_OPEN_SHM_UNLINK"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-KswfNb'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_de9c2/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_de9c2.dir/build.make CMakeFiles/cmTC_de9c2.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-KswfNb'
        Building CXX object CMakeFiles/cmTC_de9c2.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_SHM_OPEN_SHM_UNLINK  -std=c++20 -MD -MT CMakeFiles/cmTC_de9c2.dir/src.cxx.o -MF CMakeFiles/cmTC_de9c2.dir/src.cxx.o.d -o CMakeFiles/cmTC_de9c2.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-KswfNb/src.cxx
        Linking CXX executable cmTC_de9c2.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_de9c2.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_de9c2.dir/objects1.rsp -o cmTC_de9c2.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-KswfNb'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules/FindEGL.cmake:128 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiDependencies.cmake:39 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake:43 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_EGL"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OdzVUx"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OdzVUx"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_EGL"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OdzVUx'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_e1d73/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_e1d73.dir/build.make CMakeFiles/cmTC_e1d73.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OdzVUx'
        Building CXX object CMakeFiles/cmTC_e1d73.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_EGL  -std=c++20 -MD -MT CMakeFiles/cmTC_e1d73.dir/src.cxx.o -MF CMakeFiles/cmTC_e1d73.dir/src.cxx.o.d -o CMakeFiles/cmTC_e1d73.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OdzVUx/src.cxx
        Linking CXX executable cmTC_e1d73.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e1d73.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_e1d73.dir/objects1.rsp -o cmTC_e1d73.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OdzVUx'
        
      exitCode: 0
...
