
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.11.0-1018-azure - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/FindThreads.cmake:99 (CHECK_CXX_SOURCE_COMPILES)"
      - "/usr/local/share/cmake-3.31/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Dependencies.cmake:34 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:162 (include)"
      - "CMakeLists.txt:17 (find_package)"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OQxCWv"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OQxCWv"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OQxCWv'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_7b12e/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_7b12e.dir/build.make CMakeFiles/cmTC_7b12e.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OQxCWv'
        Building CXX object CMakeFiles/cmTC_7b12e.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DCMAKE_HAVE_LIBC_PTHREAD  -std=c++20 -MD -MT CMakeFiles/cmTC_7b12e.dir/src.cxx.o -MF CMakeFiles/cmTC_7b12e.dir/src.cxx.o.d -o CMakeFiles/cmTC_7b12e.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OQxCWv/src.cxx
        shared:INFO: (Emscripten: Running sanity checks)
        Linking CXX executable cmTC_7b12e.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7b12e.dir/link.txt --verbose=1
        cache:INFO: generating system asset: symbol_lists/dae99d994d603fb13aa7edd6245a890f9752f2c4.json... (this will be cached in "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cache/symbol_lists/dae99d994d603fb13aa7edd6245a890f9752f2c4.json" for subsequent builds)
        cache:INFO:  - ok
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_7b12e.dir/objects1.rsp -o cmTC_7b12e.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-OQxCWv'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapAtomic.cmake:36 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_STDATOMIC"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-ecNg5b"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-ecNg5b"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_STDATOMIC"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-ecNg5b'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_303d5/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_303d5.dir/build.make CMakeFiles/cmTC_303d5.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-ecNg5b'
        Building CXX object CMakeFiles/cmTC_303d5.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_STDATOMIC  -std=c++20 -MD -MT CMakeFiles/cmTC_303d5.dir/src.cxx.o -MF CMakeFiles/cmTC_303d5.dir/src.cxx.o.d -o CMakeFiles/cmTC_303d5.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-ecNg5b/src.cxx
        Linking CXX executable cmTC_303d5.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_303d5.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_303d5.dir/objects1.rsp -o cmTC_303d5.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-ecNg5b'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:23 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_GETTIME"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-fDxLV9"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-fDxLV9"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_GETTIME"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-fDxLV9'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_112b6/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_112b6.dir/build.make CMakeFiles/cmTC_112b6.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-fDxLV9'
        Building CXX object CMakeFiles/cmTC_112b6.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_GETTIME  -std=c++20 -MD -MT CMakeFiles/cmTC_112b6.dir/src.cxx.o -MF CMakeFiles/cmTC_112b6.dir/src.cxx.o.d -o CMakeFiles/cmTC_112b6.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-fDxLV9/src.cxx
        Linking CXX executable cmTC_112b6.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_112b6.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_112b6.dir/objects1.rsp -o cmTC_112b6.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-fDxLV9'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:34 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_SHM_OPEN_SHM_UNLINK"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-mX7TyB"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-mX7TyB"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_SHM_OPEN_SHM_UNLINK"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-mX7TyB'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_96e0a/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_96e0a.dir/build.make CMakeFiles/cmTC_96e0a.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-mX7TyB'
        Building CXX object CMakeFiles/cmTC_96e0a.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_SHM_OPEN_SHM_UNLINK  -std=c++20 -MD -MT CMakeFiles/cmTC_96e0a.dir/src.cxx.o -MF CMakeFiles/cmTC_96e0a.dir/src.cxx.o.d -o CMakeFiles/cmTC_96e0a.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-mX7TyB/src.cxx
        Linking CXX executable cmTC_96e0a.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_96e0a.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_96e0a.dir/objects1.rsp -o cmTC_96e0a.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-mX7TyB'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/Internal/CheckSourceCompiles.cmake:108 (try_compile)"
      - "/usr/local/share/cmake-3.31/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules/FindEGL.cmake:128 (check_cxx_source_compiles)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiDependencies.cmake:39 (_qt_internal_find_third_party_dependencies)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake:43 (include)"
      - "/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test HAVE_EGL"
    directories:
      source: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-dVigAL"
      binary: "/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-dVigAL"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/cmake/Modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/runner/work/wiRedPanda/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
    buildResult:
      variable: "HAVE_EGL"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-dVigAL'
        
        Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_972fb/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_972fb.dir/build.make CMakeFiles/cmTC_972fb.dir/build
        gmake[1]: Entering directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-dVigAL'
        Building CXX object CMakeFiles/cmTC_972fb.dir/src.cxx.o
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ -DHAVE_EGL  -std=c++20 -MD -MT CMakeFiles/cmTC_972fb.dir/src.cxx.o -MF CMakeFiles/cmTC_972fb.dir/src.cxx.o.d -o CMakeFiles/cmTC_972fb.dir/src.cxx.o -c /home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-dVigAL/src.cxx
        Linking CXX executable cmTC_972fb.js
        /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_972fb.dir/link.txt --verbose=1
        /home/runner/work/wiRedPanda/wiRedPanda/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_972fb.dir/objects1.rsp -o cmTC_972fb.js
        gmake[1]: Leaving directory '/home/runner/work/wiRedPanda/wiRedPanda/build/CMakeFiles/CMakeScratch/TryCompile-dVigAL'
        
      exitCode: 0
...
