// Architecture graph data: modules, nodes, edges
const modules = {
  Core:           { color: '#58a6ff', label: 'Core' },
  Element:        { color: '#da3633', label: 'Element' },
  Nodes:          { color: '#a371f7', label: 'Nodes' },
  Scene:          { color: '#3fb950', label: 'Scene' },
  Simulation:     { color: '#d29922', label: 'Simulation' },
  IO:             { color: '#79c0ff', label: 'IO' },
  UI:             { color: '#f778ba', label: 'UI' },
  BeWavedDolphin: { color: '#7ee787', label: 'BeWavedDolphin' },
  CodeGen:        { color: '#ffa657', label: 'CodeGen' },
  Components:     { color: '#f0883e', label: 'Components' },
  Tests:          { color: '#8b949e', label: 'Tests' },
  External:       { color: '#484f58', label: 'External' },
  Entry:          { color: '#238636', label: 'Entry' },
};


// ── Node data ────────────────────────────────────────────────
const nodes = [
  { id: 'main', module: 'Entry', label: 'Main.cpp', desc: 'Application bootstrap, command-line args, Qt event loop' },
  { id: 'application', module: 'Core', label: 'Application', desc: 'Singleton app state, global accessors' },
  { id: 'settings', module: 'Core', label: 'Settings', desc: 'QSettings wrapper, persistent config' },
  { id: 'common', module: 'Core', label: 'Common', desc: 'Shared utilities, helpers & types' },
  { id: 'enums', module: 'Core', label: 'Enums', desc: 'ElementType, ElementGroup, InputType enums' },
  { id: 'theme_mgr', module: 'Core', label: 'ThemeManager', desc: 'Light/Dark themes, icon management' },
  { id: 'sys_theme', module: 'Core', label: 'SystemThemeDetector', desc: 'OS theme detection' },
  { id: 'item_with_id', module: 'Core', label: 'ItemWithId', desc: 'Base class for identifiable items' },
  { id: 'priorities', module: 'Core', label: 'Priorities', desc: 'Update ordering, topological sort constants' },
  { id: 'sentry', module: 'Core', label: 'SentryHelpers', desc: 'Crash reporting, breadcrumbs' },
  { id: 'update_check', module: 'Core', label: 'UpdateChecker', desc: 'GitHub release check' },
  { id: 'status_ops', module: 'Core', label: 'StatusOps', desc: 'Tristate logic, status helpers' },
  { id: 'graphic_elem', module: 'Element', label: 'GraphicElement', desc: 'Base class for ALL circuit elements (QGraphicsItem + ItemWithId)' },
  { id: 'graphic_input', module: 'Element', label: 'GraphicElementInput', desc: 'User-interactive inputs (Button, Switch, Rotary)' },
  { id: 'elem_factory', module: 'Element', label: 'ElementFactory', desc: 'Creates elements by type string' },
  { id: 'elem_info', module: 'Element', label: 'ElementInfo', desc: 'Metadata descriptor for element types' },
  { id: 'elem_metadata', module: 'Element', label: 'ElementMetadata', desc: 'Generated element registrations' },
  { id: 'elem_label', module: 'Element', label: 'ElementLabel', desc: 'Text labels on circuit elements' },
  { id: 'prop_desc', module: 'Element', label: 'PropertyDescriptor', desc: 'Dynamic property definitions' },
  { id: 'ic', module: 'Element', label: 'IC', desc: 'Integrated Circuit — sub-circuit wrapper' },
  { id: 'ic_def', module: 'Element', label: 'ICDefinition', desc: 'Parsed .panda file, port map & logic' },
  { id: 'ic_registry', module: 'Element', label: 'ICRegistry', desc: 'Global IC cache: File → Definition' },
  { id: 'qne_port', module: 'Nodes', label: 'QNEPort', desc: 'Input/Output port on elements (QGraphicsItem)' },
  { id: 'qne_conn', module: 'Nodes', label: 'QNEConnection', desc: 'Wire between ports, signal propagation (QGraphicsItem)' },
  { id: 'scene', module: 'Scene', label: 'Scene', desc: 'QGraphicsScene — owns all elements & connections' },
  { id: 'workspace', module: 'Scene', label: 'Workspace', desc: 'Tab/document manager, multiple circuits' },
  { id: 'gfx_view', module: 'Scene', label: 'GraphicsView', desc: 'QGraphicsView — zoom, pan, select' },
  { id: 'commands', module: 'Scene', label: 'Commands', desc: 'Undo/Redo stack (10 QUndoCommand subclasses)' },
  { id: 'clipboard', module: 'Scene', label: 'ClipboardManager', desc: 'Copy/Paste serialized items' },
  { id: 'conn_mgr', module: 'Scene', label: 'ConnectionManager', desc: 'Wire creation & validation' },
  { id: 'vis_mgr', module: 'Scene', label: 'VisibilityManager', desc: 'Show/Hide element groups' },
  { id: 'prop_shortcut', module: 'Scene', label: 'PropertyShortcutHandler', desc: 'Keyboard shortcuts for element properties' },
  { id: 'simulation', module: 'Simulation', label: 'Simulation', desc: '1ms cycle timer, topological sort, 4-phase update loop' },
  { id: 'sim_blocker', module: 'Simulation', label: 'SimulationBlocker', desc: 'RAII pause guard — Suspend/Resume' },
  { id: 'serialization', module: 'IO', label: 'Serialization', desc: 'Save/Load .panda files (versioned binary QDataStream)' },
  { id: 'serial_ctx', module: 'IO', label: 'SerializationContext', desc: 'Version-aware read/write state' },
  { id: 'file_utils', module: 'IO', label: 'FileUtils', desc: 'File dialogs, path helpers' },
  { id: 'recent_files', module: 'IO', label: 'RecentFiles', desc: 'MRU file list' },
  { id: 'version_info', module: 'IO', label: 'VersionInfo', desc: 'File format version compatibility' },
  { id: 'mainwindow', module: 'UI', label: 'MainWindow', desc: 'Top-level window — menus, toolbars, status bar' },
  { id: 'mainwindow_ui', module: 'UI', label: 'MainWindowUI', desc: 'UI layout builder' },
  { id: 'elem_editor', module: 'UI', label: 'ElementEditor', desc: 'Property panel (right sidebar)' },
  { id: 'elem_editor_ui', module: 'UI', label: 'ElementEditorUI', desc: 'Editor layout' },
  { id: 'elem_palette', module: 'UI', label: 'ElementPalette', desc: 'Component palette (left sidebar)' },
  { id: 'tab_nav', module: 'UI', label: 'ElementTabNavigator', desc: 'Category tabs in palette' },
  { id: 'elem_ctx_menu', module: 'UI', label: 'ElementContextMenu', desc: 'Right-click menu on elements' },
  { id: 'sel_caps', module: 'UI', label: 'SelectionCapabilities', desc: 'Selection-aware action state' },
  { id: 'clock_dlg', module: 'UI', label: 'ClockDialog', desc: 'Clock frequency configuration' },
  { id: 'length_dlg', module: 'UI', label: 'LengthDialog', desc: 'Simulation length configuration' },
  { id: 'circuit_exp', module: 'UI', label: 'CircuitExporter', desc: 'Export to PNG/PDF' },
  { id: 'ic_dropzone', module: 'UI', label: 'ICDropZone', desc: 'Drag & drop .panda files' },
  { id: 'lang_mgr', module: 'UI', label: 'LanguageManager', desc: 'i18n / l10n Translations' },
  { id: 'trash_btn', module: 'UI', label: 'TrashButton', desc: 'Drag-to-delete UI element' },
  { id: 'labeled_slider', module: 'UI', label: 'LabeledSlider', desc: 'Slider with value label' },
  { id: 'bwd', module: 'BeWavedDolphin', label: 'BeWavedDolphin', desc: 'Waveform simulator, signal timing viewer' },
  { id: 'bwd_ui', module: 'BeWavedDolphin', label: 'BeWavedDolphinUI', desc: 'Waveform UI layout' },
  { id: 'bwd_serial', module: 'BeWavedDolphin', label: 'BWD Serializer', desc: 'Save/Load waveform data' },
  { id: 'bwd_model', module: 'BeWavedDolphin', label: 'SignalModel', desc: 'Signal data model for waveform table' },
  { id: 'bwd_delegate', module: 'BeWavedDolphin', label: 'SignalDelegate', desc: 'Custom cell rendering' },
  { id: 'bwd_waveform', module: 'BeWavedDolphin', label: 'WaveformView', desc: 'Waveform display widget' },
  { id: 'arduino_gen', module: 'CodeGen', label: 'ArduinoCodeGen', desc: 'Export circuit as Arduino C++ code' },
  { id: 'sv_gen', module: 'CodeGen', label: 'SystemVerilogCodeGen', desc: 'Export circuit as SystemVerilog HDL' },
  { id: 'grp_gate', module: 'Components', label: 'Gates', desc: 'AND, OR, NOT, NAND, NOR, XOR, XNOR, Buffer' },
  { id: 'grp_input', module: 'Components', label: 'Inputs', desc: 'Button, Switch, Rotary, Clock' },
  { id: 'grp_output', module: 'Components', label: 'Outputs', desc: 'LED, Display, 7-Segment, Buzzer' },
  { id: 'grp_memory', module: 'Components', label: 'Memory', desc: 'Flip-Flops (SR, JK, D, T), Latches' },
  { id: 'grp_mux', module: 'Components', label: 'Mux/Demux', desc: 'Multiplexers and Demultiplexers' },
  { id: 'grp_static', module: 'Components', label: 'StaticInput', desc: 'VCC, GND constants' },
  { id: 'grp_other', module: 'Components', label: 'Other', desc: 'Node, Line, Text, Truth Table' },
  { id: 'grp_ic', module: 'Components', label: 'IC Files', desc: 'Sub-circuit .panda files' },
  { id: 'test_unit', module: 'Tests', label: 'Unit Tests', desc: 'Commands, Elements, Factory, Logic, Nodes, Scene, Serialization, Simulation, UI' },
  { id: 'test_integ', module: 'Tests', label: 'Integration Tests', desc: 'Arduino, Files, IC, Simulation, Feedback, Workspace, Verilog' },
  { id: 'test_system', module: 'Tests', label: 'System Tests', desc: 'Waveform end-to-end' },
  { id: 'test_compat', module: 'Tests', label: 'Backward Compat', desc: 'Old file format loading' },
  { id: 'qt_widgets', module: 'External', label: 'Qt Widgets', desc: 'QMainWindow, QDialog, etc.' },
  { id: 'qt_graphics', module: 'External', label: 'Qt Graphics', desc: 'QGraphicsScene, QGraphicsView, QGraphicsItem' },
  { id: 'qt_core', module: 'External', label: 'Qt Core', desc: 'QTimer, QSettings, QJsonDocument, Signals/Slots' },
  { id: 'qt_test', module: 'External', label: 'Qt Test', desc: 'QTest framework' },
  { id: 'sentry_sdk', module: 'External', label: 'Sentry SDK', desc: 'Crash reporting — Crashpad/Breakpad' },
];

const edges = [
  { s: 'main', t: 'application', label: 'creates', type: 'ownership' },
  { s: 'application', t: 'mainwindow', label: 'creates', type: 'ownership' },
  { s: 'mainwindow', t: 'workspace', type: 'ownership' },
  { s: 'workspace', t: 'scene', type: 'ownership' },
  { s: 'workspace', t: 'gfx_view', type: 'ownership' },
  { s: 'scene', t: 'graphic_elem', label: 'contains', type: 'element' },
  { s: 'scene', t: 'qne_conn', label: 'contains', type: 'wiring' },
  { s: 'scene', t: 'simulation', label: 'drives', type: 'simulation' },
  { s: 'scene', t: 'commands', label: 'undo stack', type: 'ownership' },
  { s: 'scene', t: 'conn_mgr', type: 'ownership' },
  { s: 'scene', t: 'clipboard', type: 'ownership' },
  { s: 'scene', t: 'vis_mgr', type: 'ownership' },
  { s: 'simulation', t: 'graphic_elem', label: 'update cycle', type: 'simulation' },
  { s: 'simulation', t: 'qne_conn', label: 'updatePort', type: 'simulation' },
  { s: 'simulation', t: 'sim_blocker', type: 'simulation' },
  { s: 'simulation', t: 'priorities', type: 'simulation' },
  { s: 'graphic_elem', t: 'qne_port', label: 'has ports', type: 'wiring' },
  { s: 'qne_port', t: 'qne_conn', label: 'connects via', type: 'wiring' },
  { s: 'graphic_input', t: 'graphic_elem', label: 'extends', type: 'inherit' },
  { s: 'ic', t: 'graphic_elem', label: 'extends', type: 'inherit' },
  { s: 'ic', t: 'ic_def', label: 'references', type: 'element' },
  { s: 'ic_def', t: 'ic_registry', label: 'stored in', type: 'element' },
  { s: 'graphic_elem', t: 'item_with_id', label: 'extends', type: 'inherit' },
  { s: 'graphic_elem', t: 'status_ops', type: 'element' },
  { s: 'graphic_elem', t: 'elem_label', type: 'element' },
  { s: 'elem_factory', t: 'graphic_elem', label: 'creates', type: 'element' },
  { s: 'elem_factory', t: 'elem_info', type: 'element' },
  { s: 'elem_info', t: 'elem_metadata', type: 'element' },
  { s: 'elem_factory', t: 'enums', type: 'element' },
  { s: 'grp_gate', t: 'elem_factory', type: 'component' },
  { s: 'grp_input', t: 'elem_factory', type: 'component' },
  { s: 'grp_output', t: 'elem_factory', type: 'component' },
  { s: 'grp_memory', t: 'elem_factory', type: 'component' },
  { s: 'grp_mux', t: 'elem_factory', type: 'component' },
  { s: 'grp_static', t: 'elem_factory', type: 'component' },
  { s: 'grp_other', t: 'elem_factory', type: 'component' },
  { s: 'grp_ic', t: 'ic', type: 'component' },
  { s: 'serialization', t: 'serial_ctx', type: 'io' },
  { s: 'serialization', t: 'version_info', type: 'io' },
  { s: 'serialization', t: 'graphic_elem', label: 'save/load', type: 'io' },
  { s: 'serialization', t: 'qne_conn', label: 'save/load', type: 'io' },
  { s: 'scene', t: 'serialization', label: 'file I/O', type: 'io' },
  { s: 'mainwindow', t: 'file_utils', type: 'io' },
  { s: 'mainwindow', t: 'recent_files', type: 'io' },
  { s: 'mainwindow', t: 'mainwindow_ui', type: 'ui' },
  { s: 'mainwindow', t: 'elem_editor', type: 'ui' },
  { s: 'mainwindow', t: 'elem_palette', type: 'ui' },
  { s: 'mainwindow', t: 'circuit_exp', type: 'ui' },
  { s: 'mainwindow', t: 'lang_mgr', type: 'ui' },
  { s: 'mainwindow', t: 'sel_caps', type: 'ui' },
  { s: 'mainwindow', t: 'ic_dropzone', type: 'ui' },
  { s: 'elem_editor', t: 'elem_editor_ui', type: 'ui' },
  { s: 'elem_editor', t: 'prop_desc', type: 'ui' },
  { s: 'elem_palette', t: 'tab_nav', type: 'ui' },
  { s: 'elem_palette', t: 'elem_factory', label: 'populates from', type: 'ui' },
  { s: 'gfx_view', t: 'elem_ctx_menu', type: 'ui' },
  { s: 'gfx_view', t: 'prop_shortcut', type: 'ui' },
  { s: 'mainwindow', t: 'bwd', label: 'opens', type: 'bwd' },
  { s: 'bwd', t: 'bwd_ui', type: 'bwd' },
  { s: 'bwd', t: 'bwd_serial', type: 'bwd' },
  { s: 'bwd', t: 'bwd_model', type: 'bwd' },
  { s: 'bwd_model', t: 'bwd_delegate', type: 'bwd' },
  { s: 'bwd', t: 'bwd_waveform', type: 'bwd' },
  { s: 'bwd', t: 'scene', label: 'simulates', type: 'bwd' },
  { s: 'bwd', t: 'simulation', label: 'drives', type: 'bwd' },
  { s: 'mainwindow', t: 'arduino_gen', label: 'export', type: 'codegen' },
  { s: 'mainwindow', t: 'sv_gen', label: 'export', type: 'codegen' },
  { s: 'arduino_gen', t: 'scene', label: 'reads', type: 'codegen' },
  { s: 'sv_gen', t: 'scene', label: 'reads', type: 'codegen' },
  { s: 'application', t: 'settings', type: 'core' },
  { s: 'application', t: 'sentry', type: 'core' },
  { s: 'application', t: 'theme_mgr', type: 'core' },
  { s: 'application', t: 'update_check', type: 'core' },
  { s: 'theme_mgr', t: 'sys_theme', type: 'core' },
  { s: 'test_unit', t: 'graphic_elem', type: 'test' },
  { s: 'test_unit', t: 'scene', type: 'test' },
  { s: 'test_unit', t: 'simulation', type: 'test' },
  { s: 'test_integ', t: 'workspace', type: 'test' },
  { s: 'test_integ', t: 'serialization', type: 'test' },
  { s: 'test_integ', t: 'arduino_gen', type: 'test' },
  { s: 'test_system', t: 'bwd', type: 'test' },
  { s: 'test_compat', t: 'serialization', type: 'test' },
  { s: 'test_unit', t: 'qt_test', type: 'external' },
  { s: 'mainwindow', t: 'qt_widgets', type: 'external' },
  { s: 'scene', t: 'qt_graphics', type: 'external' },
  { s: 'graphic_elem', t: 'qt_graphics', type: 'external' },
  { s: 'simulation', t: 'qt_core', type: 'external' },
  { s: 'application', t: 'qt_core', type: 'external' },
  { s: 'sentry', t: 'sentry_sdk', type: 'external' },
];

