# Copyright 2015 - 2024, GIBIS-Unifesp and the WiRedPanda contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Deploy

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

# =================================

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Qt 32bit
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v4
      with:
        version: 5.15.2
        cache: true
        arch: win32_msvc2019

    - name: Install Qt 64bit
      if: matrix.os != 'windows-latest'
      uses: jurplel/install-qt-action@v4
      with:
        version: 5.15.2
        cache: true

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}

# =================================

    - name: Build Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt install libgstreamer-gl1.0-0 libfuse2 libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxkbcommon-dev libxkbcommon-x11-dev
        mkdir build
        cd build
        qmake ../WPanda.pro
        make -j2

    - name: Test Ubuntu
      if: runner.os == 'Linux'
      run: |
        cd build/test
        ./WPanda-test -platform offscreen

    - name: linuxdeployqt
      if: runner.os == 'Linux'
      run: |
        mkdir appimage
        cp app/resources/wpanda.desktop appimage/wpanda.desktop
        cp app/resources/wpanda.svg appimage/wpanda_icon.svg
        cp build/app/wiredpanda appimage
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x ./linuxdeployqt-continuous-x86_64.AppImage
        VERSION=4 ./linuxdeployqt-continuous-x86_64.AppImage appimage/wiredpanda -appimage
        rm ./linuxdeployqt-continuous-x86_64.AppImage
        mv WiRedPanda-4-x86_64.AppImage WiRedPanda-Ubuntu-Qt5.AppImage

    - name: Publish Ubuntu
      uses: softprops/action-gh-release@v2
      if: runner.os == 'Linux'
      with:
        fail_on_unmatched_files: true
        files: '*.AppImage'

# =================================

    - name: Setup MSVC Toolchain
      if: startsWith(matrix.os, 'windows')
      uses: pbeast/gha-setup-vsdevenv@master
      with:
        arch: x86

    - name: Build Windows
      if: runner.os == 'Windows'
      run: |
        choco install jom
        mkdir build
        cd build
        qmake ../WPanda.pro
        jom

    - name: Test Windows
      if: runner.os == 'Windows'
      run: |
        cd build
        jom check

    - name: windeployqt
      if: runner.os == 'Windows'
      run : |
        cp -r examples build/app/release
        cd build/app/release
        windeployqt --compiler-runtime wiredpanda.exe
        rm wiredpanda_pch.obj
        rm wiredpanda_pch.pch
        cd ..
        ren release wpanda
        Compress-Archive -Path wpanda -DestinationPath WiRedPanda-Windows-Qt5-Portable.zip

    - name: Publish Windows
      uses: softprops/action-gh-release@v2
      if: startsWith(matrix.os, 'windows')
      with:
        fail_on_unmatched_files: true
        files: 'build/app/*.zip'

# =================================
# https://bugreports.qt.io/browse/QTBUG-117225

    - name: Build macOS
      if: runner.os == 'macOS'
      run: |
        mkdir build
        cd build
        qmake ../WPanda.pro -early QMAKE_DEFAULT_LIBDIRS=$(xcrun -show-sdk-path)/usr/lib
        make -j3

    - name: Test macOS
      if: runner.os == 'macOS'
      run: |
        cd build
        make check

    - name: macdeployqt
      if: runner.os == 'macOS'
      run: |
        cd build/app
        macdeployqt wiredpanda.app -dmg
        mv wiredpanda.dmg WiRedPanda-macOS-Qt5.dmg

    - name: Publish macOS
      uses: softprops/action-gh-release@v2
      if: runner.os == 'macOS'
      with:
        fail_on_unmatched_files: true
        files: 'build/app/*.dmg'
