name: Update Qt Translations

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.0
          cache: true
          aqtversion: ==3.2.*
          modules: qtmultimedia

      - name: Run lupdate
        run: |
          lupdate WPanda.pro

      - name: Commit and push if translation files changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if ! git diff --quiet; then
            git add app/resources/translations/*.ts
            git commit -m "Update translation files via lupdate"
            git fetch origin ${{ github.head_ref }}
            git rebase origin/${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No translation updates needed"
          fi
