name: Update Qt Translations

on:
  push:
    branches:
      - master

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.0
          cache: true
          aqtversion: ==3.2.*

      - name: Run lupdate
        run: |
          lupdate WPanda.pro

      - name: Commit updated .ts files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/resources/translations/*.ts
          git commit -m "Update translation source files via lupdate" || echo "No changes"
          git push
