# Copyright 2015 - 2025, GIBIS-Unifesp and the wiRedPanda contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build WebAssembly

on:
  push:
    branches:
      - wasm

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Qt for WASM
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.9.0
        host: all_os
        target: wasm
        arch: wasm_multithread
        modules: qtmultimedia qtimageformats
        extra: --autodesktop
        cache: true
        
    - name: Setup emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk
        cd emsdk
        ./emsdk install 3.1.70
        ./emsdk activate 3.1.70

    - name: Install Ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: wasm-ubuntu-6.9.0

    - name: Build WASM
      run: |
        source ./emsdk/emsdk_env.sh
        mkdir build
        cd build
        qt-cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja
        ninja wiredpanda
        cp wiredpanda.html index.html
        wget https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.min.js
        sed -i '/<script src="wiredpanda.js"><\/script>/a <script src="coi-serviceworker.min.js"><\/script>' index.html

    - name: Commit to site branch
      if: success()
      run: |
        # Configure Git with your user details
        git config --global user.name "Rodrigo Torres"
        git config --global user.email "5768540+darktorres@users.noreply.github.com"

        # Checkout the site branch
        git checkout site

        # Copy the built files to the public folder
        mkdir -p ./public/wasm
        cp -r ./build/* ./public/wasm/

        # Stage and commit the changes
        git add ./public/wasm/
        git commit -m "Deploy WASM files"

        # Push changes to the site branch
        git push origin site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger site deployment workflow
      run: |
        curl -X POST \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/site.yml/dispatches \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{"ref": "site"}'

